### ISSUE TITLE
Add documentation for ServiceMonitor.exe

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/iis-docker#1]
In the base IIS image, we use `ServiceMonitor.exe` to monitor the `we3svc` service. We need to document this.

**Comment by shirhatti** [comment]
cc @pan-wang

**Comment by StefanScherer** [comment]
@shirhatti The `ServiceMonitor.exe` seems like a better solution than the `Wait-Service.ps1` script from https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/Wait-Service. Right?
Is there any source code on GitHub available for the tool?
Can others use it to monitor another Windows Service in their Docker images?

**Comment by shirhatti** [comment]
@StefanScherer Currently you can `ServiceMonitor.exe` to monitor other WIndows Service in your Docker images, however that is not a scenario we have extensively tested.

We are **very** strongly leaning towards releasing the source for ServiceMonitor on GitHub, but I don't have any concrete dates to share just yet. And yes, the IIS team intends for it to be a better solution than `Wait-Service.ps1` 😄

**Comment by StefanScherer** [comment]
@shirhatti Thank you!

**Comment by shirhatti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add docs for ServiceMonitor.exe](https://trello.com/c/q6e0qLwK/4-add-docs-for-servicemonitor-exe)

**Comment by sixeyed** [comment]
@shirhatti any update on making the source for `ServiceMonitor` available? It would be great to standardise on one tool for this, and if it had its own repo we could extend it (e.g. adding a web server to the `ServiceMonitor` so we could check service status from outside the container).

**Comment by shirhatti** [comment]
@sixeyed Nothing yet, but hang tight. I promise it's on the way.

**Comment by thegreatjerboa** [comment]
@shirhatti Any update?

**Comment by shirhatti** [comment]
See https://github.com/Microsoft/IIS.ServiceMonitor
