### ISSUE TITLE
how to use the 64 bit version of IIS in container

### ISSUE THREAD

**Issue by zhangjixin** [Microsoft/iis-docker#102]
Hi,

I have a project which need to use the 64 bit version of IIS to run it. I used to select the "Use the 64 bit version of IIS Express for web sites and projects" in Visual Studio before running my project. 
![image](https://user-images.githubusercontent.com/6881149/40035031-372abfec-5832-11e8-9978-0f0807767177.png)

But when I prepare to use docker for windows to deploy my project, I just don't know how to config it to use 64 bit version of IIS for the container, then it results that my project can't running in the docker environment. Could you please give me a hand on this?  What can I do to running my project in the docker?

Thanks.

**Comment by shirhatti** [comment]
@zhangjixin Our containers already default to running IIS worker process as 64-bit processes.
