### ISSUE TITLE
New to Docker for Windows.

### ISSUE THREAD

**Issue by nexusguy59** [Microsoft/iis-docker#104]
Hello Guys,

I have this working properly finally on my Docker for Windows Server. I am using your iis-docker, how do I use it for multiple websites? I have three websites that I would like to use this one container for.

Thank you for your time and help.
Michael

**Comment by shirhatti** [comment]
@nexusguy59 What are you trying to accomplish? It's considered an anti-pattern to run multiple websites in a single docker container and our published images don't necessarily optimize for that scenario.

Is there a tight coupling between your websites that require to live in the same container? If not, have you considered running them in separate containers?

**Comment by nexusguy59** [comment]
Makes sense, I am just used to putting I havw to develope new mind set is
all
