### ISSUE TITLE
.NET Framework 4.7.2 in Windows Server 2016 amd64 tag

### ISSUE THREAD

**Issue by TiagoLeao** [Microsoft/iis-docker#108]
Hi,

There are any plans to include .NET Framework 4.7.2 in Windows Server 2016 amd64 tag for Microsoft/iis-docker?

That support seems to be already provided in the other versions (1709 and 1803).

Best regards

**Comment by shirhatti** [comment]
None so far.

If you're using ASP.NET, you're probably better served using https://github.com/microsoft/aspnet-docker#windows-server-2016-amd64-tags where we do already have a 4.7.2 Windows Server 2016 image
