### ISSUE TITLE
Downloading: Unknown blob

### ISSUE THREAD

**Issue by b-overgard** [Microsoft/iis-docker#11]
Windows 7, docker toolbox 1.12.2. Going to test again with 1.13. Using the dockerfile from the readme.

$ docker -v
Docker version 1.12.2, build bb80604

$ uname -a
MINGW64_NT-6.1 <Computer Name Here> 2.3.0(0.290/5/3) 2015-09-29 10:48 x86_64 Msys

$ docker build -t iis-site .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM microsoft/iis
latest: Pulling from microsoft/iis
9c7f9c7d9bc2: Retrying in 1 second
d33fff6043a1: Downloading
b7c3bbe47489: Download complete
1028e286eae2: Download complete
28e6f26ee039: Download complete
unknown blob

**Comment by shirhatti** [comment]
Can you try running `& 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon`?
Make sure you are using windows daemon and not linux

**Comment by ateimoo** [comment]
I just tried running Docker Toolbox on Windows 10 Home.
Docker runs but you can't pull any Windows images since you're piping all commands through a Linux VM (on Virtualbox) and so the daemon is linux!!! This is not mentioned anywhere!!! Ridiculous...

**Comment by b-overgard** [comment]
Devs, please note in the readme that the image does not run with docker toolbox. A full install of docker is needed.

**Comment by shirhatti** [comment]
@ateimoo I understand your frustration, however we do mention in the README that [microsoft/iis is a Windows container image](https://github.com/Microsoft/iis-docker#iis-docker-image).
Your feedback is duly noted, we will consider revising the readme or adding an FAQ to bring attention to the issue that you bring up

**Comment by jontreynes** [comment]
I am having the same issue trying to build iis with image2docker
PS C:\i2d2\iis> docker build -t i2d2/app_vm .
Sending build context to Docker daemon 21.42 MB

Step 1/10 : FROM microsoft/aspnet:windowsservercore-10.0.14393.1066
windowsservercore-10.0.14393.1066: Pulling from microsoft/aspnet
3889bb8d808b: Pulling fs layer
6d4d50238ed1: Pulling fs layer
0606d7d474d1: Pulling fs layer
672755d284cd: Pulling fs layer
88f5b9741695: Pulling fs layer
d53dd94c8474: Pulling fs layer
fb288ca707aa: Pulling fs layer
672755d284cd: Waiting
88f5b9741695: Waiting
d53dd94c8474: Waiting
fb288ca707aa: Waiting
6d4d50238ed1: Downloading
3889bb8d808b: Downloading
672755d284cd: Verifying Checksum
672755d284cd: Download complete
88f5b9741695: Download complete
d53dd94c8474: Verifying Checksum
d53dd94c8474: Download complete
0606d7d474d1: Verifying Checksum
0606d7d474d1: Download complete
fb288ca707aa: Verifying Checksum
fb288ca707aa: Download complete
docker : unknown blob
At line:1 char:1
+ docker build -t i2d2/app_vm .
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (unknown blob:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by jontreynes** [comment]
Wow, I'm dumb. I didn't run the SwitchDaemon with '&' which is suppose to restart your machine. That worked for me.
It would be nice if the build told you that you might be running the wrong daemon because unknown blob is not very helpful

**Comment by shirhatti** [comment]
Closing. Feel free to re-open if you still have issues
