### ISSUE TITLE
Refresh / Push image for windowsservercore-1803

### ISSUE THREAD

**Issue by jmajoor** [Microsoft/iis-docker#110]
A new image for windowsservercore-1803 was pushed a few days ago, but there is no equivalent refresh for IIS. 
Can you refresh the image to reflect the latest windows server core state?
Can you include it in the automated builds (so the IIS image stays in sync)

- Johan

**Comment by mcy94w** [comment]
Hi jmajoor:

Apologize for the delay. The refreshed images are available now. We are working on the build pipeline to automate the build and publish.

Thanks
