### ISSUE TITLE
Local volume not bind with container 

### ISSUE THREAD

**Issue by SK5277-SINGH** [Microsoft/iis-docker#113]
OS:Win 10 Pro

My IIS Docker file:
```
FROM microsoft/iis:latest
RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*
WORKDIR /inetpub/wwwroot
COPY content/ .
EXPOSE 80
```
Build command:
`C:\Users\admin\Desktop\iis-demo>docker build -t iis-image .`

> Sending build context to Docker daemon  6.656kB
> Step 1/5 : FROM microsoft/iis:latest
>  ---> 248afbbe0fd1
> Step 2/5 : RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*
>  ---> Using cache
>  ---> 880273c74891
> Step 3/5 : WORKDIR /inetpub/wwwroot
>  ---> Using cache
>  ---> a07a920df3bf
> Step 4/5 : COPY content/ .
>  ---> ab16da97c523
> Step 5/5 : EXPOSE 80
>  ---> Running in 98b7cbef83c9
> Removing intermediate container 98b7cbef83c9
>  ---> 1c7d232a73aa
> Successfully built 1c7d232a73aa
> Successfully tagged iis-image:latest

Run Command:
`C:\Users\admin\Desktop\iis-demo>docker run -d -p 8080:80 -v C:\Users\admin\Desktop\iis-demo\content:/inetpub/wwwroot iis-image`

**i also tried with:**
`C:\Users\admin\Desktop\iis-demo>docker run -d -p 8080:80 -v C:\\Users\\admin\\Desktop\\iis-demo\\content:/inetpub/wwwroot iis-image`

**But everytime I am getting following error:**
> docker: Error response from daemon: invalid volume specification: 'C:\Users\admin\Desktop\iis-demo\content:/inetpub/wwwroot'.
> See 'docker run --help'.

**Comment by JWasdin** [comment]
Try this command which included the `c:` and changed the direction of your slashes for the remote location:

`docker run -d -p 8080:80 -v C:\Users\admin\Desktop\iis-demo\content:c:\inetpub\wwwroot iis-image`

**Comment by SK5277-SINGH** [comment]
I tried according your suggestion and docker run successfully but when I checked with container IP on browser it gives error
Like below:

> 401 - Unauthorized: Access is denied due to invalid credentials.
> You do not have permission to view this directory or page using the credentials that you supplied. 
>

**Comment by JWasdin** [comment]
I am actually running in to the same issue. I am also able to get the container to mount the local folder, however, whether I overwrite the `wwwroot` folder or add the mounted folder as a subdirectory within `wwwroot`, I recieve the same 401 error.

I have been trying to adjust the `Anonymous Authentication` but no success yet.Hopefully the devs here can help resolve this for us both.

**Comment by bariscaglar** [comment]
@JWasdin is your mounted directory under C:\users as well? Also @SK5277-SINGH and @JWasdin can you report on which OS you're on (Result on Winver)?

**Comment by JWasdin** [comment]
@bariscaglar I actually mounted a subdirectory within the `wwwroot`. I had an index.html file in this subdir, and when I shifted the html file to another name it seemed to resolve the issue. Not certain why this was the case.

Running on Win10 Pro

**Comment by mcy94w** [comment]
Hi @JWasdin :
Please make sure you don't have conflict files between the source folder and the target folder.

**Comment by JWasdin** [comment]
@mcy94w The target folder is not created until the source folder is mounted so I don't think there should be any conflict between the files given they are added to subdirs instead of the `wwwroot`.

**Comment by mcy94w** [comment]
@JWasdin  I see. Could you please paste the result for `(Get-Acl c:/path/to/your/mapped/file).Access`

**Comment by JWasdin** [comment]
@mcy94w 

Here is the requested response, scrubbed a bit since it is a work station:

```
FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : domain\user
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None
```

**Comment by mcy94w** [comment]
Hi @JWasdin :

I see. In this case BUILTIN\Users does not have access to the file. As a result, IIS will not have access. I don't think any folder under user profile will be accessible if map to container.

**Comment by shirhatti** [comment]
@JWasdin Can you trying either volume mounting a directory that BUILTIN\Users has access to OR grant access to BUILTIN\Users on the directory that you are trying to volume mount into your container.

There's not much IIS can do at this to mitigate the issue you're seeing

**Comment by bestickley** [comment]
Giving full control to Everyone on the host source folder worked for me.
