### ISSUE TITLE
Allow to View Detailed Error when using Containers when web.config in app does not work.

### ISSUE THREAD

**Issue by kbdavis07** [Microsoft/iis-docker#114]
**Currently I am getting this:**

![image](https://user-images.githubusercontent.com/5434970/43380410-13f8a374-939f-11e8-9d68-cd0350b4d890.png)

**Even through my web app has this in the web.config file:**

![image](https://user-images.githubusercontent.com/5434970/43380489-4f67e672-939f-11e8-9d0a-5f7b3d0ef8c8.png)

![image](https://user-images.githubusercontent.com/5434970/43380498-59c79766-939f-11e8-83be-dec81094ff74.png)

On the Server: 

![image](https://user-images.githubusercontent.com/5434970/43383430-f53a31b4-93a8-11e8-8599-55ccd34ade37.png)

Would like to enable showing Errors in Docker so I can figure out what the issue is.

Thanks,

Brian Davis

**Comment by shirhatti** [comment]
```xml
<configuration>
  <system.web>
    <customErrors mode="Off" />
  </system.web>

  <system.webServer>
    <httpErrors errorMode="Detailed" />
  </system.webServer>
</configuration>
```

**Comment by shirhatti** [comment]
@kbdavis07 It's conceivable that you aren't even hitting the custom error module. You may be hitting be hitting an error like malformed config that prevents the error module from even being initialized.

You could try enabling FREB to what's setting the 500 error.

Are you able to see detailed error pages for let's say HTTP 4xx responses?

**Comment by shirhatti** [comment]
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more   details and are encountering this issue please add a new reply and re-open   the issue.
