### ISSUE TITLE
Overview information host port mapping incorrect

### ISSUE THREAD

**Issue by lwsrbrts** [Microsoft/iis-docker#117]
Perhaps I've missed something but should this in the example: 

`docker run -d -p 8000:8000 --name my-running-site iis-site`

Not instead be:

`docker run -d -p 8000:80 --name my-running-site iis-site`

Since the only exposed port in the Dockerfile is 80, mapping to the container on 8000 won't work.

**Comment by wsc9108** [comment]
Agree, I test and find the same!

**Comment by shirhatti** [comment]
0caffd519f01c876d7e4d9e937f700564b2f4115
