### ISSUE TITLE
How to install smtp feature?

### ISSUE THREAD

**Issue by gprashanthkumar** [Microsoft/iis-docker#126]
Hi,
Any idea on getting  SMTP service enabled on IIS-docker? without which we cannot take our site onto container.

**Comment by bariscaglar** [comment]
SMTP is not owned by the IIS team, but it would be enabled just as well as any feature using [dism](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/enable-or-disable-windows-features-using-dism) or PS Cmdlet [Enable-WindowsOptionalFeature](https://docs.microsoft.com/en-us/powershell/module/dism/enable-windowsoptionalfeature?view=win10-ps). 

[Here](https://github.com/Microsoft/iis-docker/tree/master/samples/php) is a link that contains an example for enabling FastCGI using dism.
