### ISSUE TITLE
Install MSI error, how to install it?

### ISSUE THREAD

**Issue by alexsandro-xpt** [Microsoft/iis-docker#13]
I'm trying build my own image from this `FROM microsoft/iis` with this Dockerfile:
```
FROM microsoft/iis
SHELL ["powershell", "-command"]

# Install ASP.NET
RUN Install-WindowsFeature NET-Framework-45-ASPNET; `  
    Install-WindowsFeature Web-Asp-Net45

RUN mkdir C:\cry

COPY CRRuntime_64bit_13_0_5.msi C:\cry

RUN ["msiexec.exe", "/i", "C:\\cry\\CRRuntime_64bit_13_0_5.msi", "/qn"]
# Configure website
EXPOSE 80
```

But, when install the Crystal Report MSI, I get an error:
`Step 9/13 : RUN msiexec.exe /i C:\cry\CRRuntime_64bit_13_0_5.msi /qn ---> Running in 7afd22e7a600The command 'msiexec.exe /i C:\cry\CRRuntime_64bit_13_0_5.msi /qn' returned a non-zero code: 1603`

Whats is wrong ?
The MSI Crystal Reports file is: https://apurafacil.blob.core.windows.net/candidatos/CRRuntime_64bit_13_0_5.msi

**Comment by hqer2k9** [comment]
Hey There, i got a similar error while running a different exe (appcmd for iis) and the reason it failed was because i didn't gave the full path to the exe, hope it helps.

**Comment by alexsandro-xpt** [comment]
My exe is a `msiexec.exe`. Are you tould me, I should put a full path like this? `c:\windows\system32\msiexec.exe`

**Comment by hqer2k9** [comment]
Hey there,

you have to tell the MSI installer to run in queit and passive mode like this, since it cannot display a UI and so on

`RUN msiexec C:\Cry\CRRuntime_64bit_13_0_5.msi /quiet /qn /passive`

you can also use the ADD command if its a internet download, like this:
`ADD https://apurafacil.blob.core.windows.net/candidatos/CRRuntime_64bit_13_0_5.msi`
so you dont have to manually add it

hope that helps, worked at least for me installing MSI stuff

**Comment by Novex** [comment]
@alexsandro-xpt did you ever end up getting the Crystal Reports runtime installed?

I'm seeing the same problems you mentioned here and [in this forum thread](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/792e7300-9b59-420c-b1bb-ece6d2142966/error-install-msi-at-microsoftiis-image).

**Comment by alexsandro-xpt** [comment]
@Novex no success yet, the trully is I stop to try.

**Comment by shirhatti** [comment]
@alexsandro-xpt I'm going to close this issue since it's not relevant to IIS.
@PatrickLang Is there a general forum where I can redirect folks to, who just have questions about container in general

**Comment by ktsangop** [comment]
Sorry to bump this closed issue, but there is a workaround described on the link below that worked for me, and i hope it helps anyone else. Just to clarify, i am using this container https://github.com/Microsoft/aspnet-docker but it should work on the one @alexsandro-xpt is using.

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/20588e86-c8fa-450a-8dad-77484eb9ef39/windows-2016-container-and-crystal-reports-runtime?forum=windowscontainers
