### ISSUE TITLE
Cannot attached to container

### ISSUE THREAD

**Issue by dlhansford** [Microsoft/iis-docker#14]
Whenever I start a new container in interactive mode, I find myself stuck at the "Service 'w3svc' started" prompt and am unable to navigate away from there. Unless I Ctrl-C to stop the container.

**Comment by shirhatti** [comment]
You can override the entrypoint at docker run time from `ServiceMonitor.exe` to something else. Try this example below

```
docker run -it --entrypoint powershell microsoft/iis
```
