### ISSUE TITLE
A device attached to the system is not functioning. (Exception from HRESULT: 0x8007001F)

### ISSUE THREAD

**Issue by sirdank** [Microsoft/iis-docker#144]
I get this error when doing a number of different things, namely, `test-connection $env:computer' in a powershell prompt. Steps to reproduce:

1. Provision a "Server 2016 With Containers" VM in azure with a premium storage managed disk. Format the disk using powershell:

	$driveletter = "f"
	$folder = "Data"
	$name = "data"
	$VDname = "data"

	$numberofdisks = 1
	$storagesubFriendlyName = Get-StorageSubSystem 

	#get specific disks if more than what you want is available in the pool this will get all disks that are primordial
	$PoolCount = Get-PhysicalDisk -CanPool $True 

	if ($PoolCount -is [array]) {
		$numberofdisks = $PoolCount.Count
	}

	Write-Host "using $numberofdisks for numberofcolumns"
	$PhysicalDisks = Get-PhysicalDisk -CanPool $True

	$pool = New-StoragePool -FriendlyName $name `
		-StorageSubSystemFriendlyName $storagesubFriendlyName.FriendlyName -PhysicalDisks $PhysicalDisks

	$vDisk = New-VirtualDisk -StoragePoolFriendlyName $pool.FriendlyName -FriendlyName $VDname -Interleave 65536 `
		-NumberOfColumns $numberofdisks -ResiliencySettingName Simple -UseMaximumSize

	$disk = Initialize-Disk -VirtualDisk $vDisk -PartitionStyle GPT -PassThru
	New-Partition -DiskNumber $disk.Number -DriveLetter $driveletter -UseMaximumSize
	Format-Volume -FileSystem NTFS -NewFileSystemLabel $name -AllocationUnitSize 65536 `
		-Confirm:$false -DriveLetter $driveletter

2. Add "data-root":"F:\\docker" to your C:\ProgramData\docker\config\daemon.json
3. Get-Service *docker* | Restart-Service
4. PS C:\> docker run -d microsoft/iis
5. PS C:\> docker exec -it CONTAINERNAME powershell
6. PS C:\> test-connection $env:computername
test-connection : A device attached to the system is not functioning. (Exception from HRESULT: 0x8007001F)
At line:1 char:1
+ test-connection $env:computername
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Test-Connection], COMException
    + FullyQualifiedErrorId : TestConnectionException,Microsoft.PowerShell.Commands.TestConnectionCommand

**Comment by shirhatti** [comment]
It looks a transient failure with you infrastructure. Do you mind re-trying? If the problem persists, you're better off reaching out to Azure support.

**Comment by sirdank** [comment]
@shirhatti I understand. I'm not frustrated but couldn't find a github for the windowsservercore image team and thought this might be close enough. Thank you for clarifying that you all are the IIS folks. I've submitted an azure support ticket.

**Comment by shirhatti** [comment]
Just FYI, this is the forum for Windows containers support- https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers

**Comment by shirhatti** [comment]
It is linked to from their DockerHub README page- https://hub.docker.com/_/microsoft-windows-base-os-images
