### ISSUE TITLE
ERROR: Failed to start or query status of service 'w3svc' error, while setting IIS Web Application authentication

### ISSUE THREAD

**Issue by StephenMolloy** [microsoft/iis-docker#146]
_From @suseendare on Thursday, 31 January 2019 09:56:48_

Trying to update authentication of Web Application in IIS, using Powershell via dockerfile. 
Tried directly using RUN instruction as well as using a ps1 file.

`Set-WebConfigurationProperty -Filter "/system.webServer/security/authentication/anonymousAuthentication" -Name Enabled -Value False -PSPath IIS:\ -Location "'Default Web Site/MyWebApp'";
    Set-WebConfigurationProperty -Filter "/system.webServer/security/authentication/basicAuthentication" -Name Enabled -Value False -PSPath IIS:\ -Location "'Default Web Site/MyWebApp'";
    Set-WebConfigurationProperty -Filter "/system.webServer/security/authentication/windowsAuthentication" -Name Enabled -Value True -PSPath IIS:\ -Location "'Default Web Site/MyWebApp'"; `

W3SVC stops. If the same commands are run in interactive terminal mode, the commands work fine and W3SVC does not stop. It fails only while using dockerfile.

This is happening in below images:
- mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2016
- microsoft/aspnet

dockerfile available in below link:
[https://stackoverflow.com/questions/54333074/aspnet-docker-image-updating-authentication-using-powershell-stops-w3svc](url)

_Copied from original issue: Microsoft/aspnet-docker#160_

**Comment by Vaccano** [comment]
This is happening with a ltsc2019 based container for me.

**Comment by danassetms** [comment]
This is happening with a ltsc2019 based container for me too
Some work and some randomly crash - any fix?
