### ISSUE TITLE
ServiceMonitor 'APPCMD failed with error code 183' @ docker start for aspnet:4.7.2-windowsservercore-ltsc2016

### ISSUE THREAD

**Issue by liberdis** [microsoft/iis-docker#148]
FROM microsoft/aspnet:4.7.2-windowsservercore-ltsc2016
create a container with some docker run -e environment variables.
docker stop container
docker start container
expected result: container enters and maintains running state
actual result: container crashes, producing error at tail of log when servicemonitor attempts to start up: 'APPCMD failed with error code 183'

known workarounds:
The July-2017 1.1.0.1 version also caused the same symptom and I have had to roll back to [1.0.0.1](https://github.com/Microsoft/iis-docker/raw/8ffb45926630255cff635b6c693e0efd43a96aa7/windowsservercore/ServiceMonitor.exe) in order to restart my containers because apparently that version does not attempt to update app.config

I have found numerous "duplicate issues" that have been closed yet the issue remains without a clear answer other than to roll back. Most seem to refer back to [iis-docker#42](https://github.com/Microsoft/iis-docker/issues/42) which is closed, citing a July-2017 update however it seems some problems remain

If anyone has any ideas as to what I might try to allow 2.0.1.6 to work in ltsc2016 please let me know and thanks in advance for the help

**Comment by bariscaglar** [comment]
Can you post your exact dockerfile and the docker run command you use? I recently closed a similar issue in this repo. Perhaps it could provide an answer?

**Comment by pf56** [comment]
For what it's worth, I am running in to the same error message if I try to restart a container after editing the web.config file.

```
$ docker run -d -p 8000:80 --name aspnet_sample mcr.microsoft.com/dotnet/framework/samples:aspnetapp
$ docker exec -it aspnet_sample powershell
<edit web.config through powershell>
<refreshing the page in the browser confirms that it is still functional>
$ docker stop aspnet_sample
$ docker start aspnet_sample
$ docker logs aspnet_sample

 Service 'w3svc' has been stopped

APPCMD failed with error code 183

Failed to update IIS configuration
```

The container is now broken and refuses to start.

**Comment by dbaltor** [comment]
Run into the same error with `dotnet/framework/aspnet:3.5`  image when trying to restart IIS. As already said, the workaround is to downgrade to an old ServiceMonitor version found [here](https://github.com/Microsoft/iis-docker/raw/8ffb45926630255cff635b6c693e0efd43a96aa7/windowsservercore/ServiceMonitor.exe).

**Comment by triynko** [comment]
This is preventing tasks from launching correctly in AWS ECS, using the microsoft base image.
