### ISSUE TITLE
Nano Server image for 1809?

### ISSUE THREAD

**Issue by sixeyed** [Microsoft/iis-docker#149]
The latest 1809 image only has a Windows Server Core variant - `mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019`. Is there going to be a Nano Server image update?

**Comment by shirhatti** [comment]
Unfortunately, no. We've dropped support for IIS on Nano after ltsc2016. Part of reducing the image size in the Windows base image meant IIS no longer tenable.
