### ISSUE TITLE
Connect to Dockerized IIS remotely

### ISSUE THREAD

**Issue by hmdhasani** [Microsoft/iis-docker#15]
Is there any way to connect to the inside container IIS from an IIS Manager so I could have a GUI Access to that IIS?

**Comment by hmdhasani** [comment]
I followed this:
https://technet.microsoft.com/en-us/library/dn198619.aspx
and it seems that my IIS Manager could see the IIS but I got Authentication error. It seems the user must be ContainerManager but I don't know the password

**Comment by shirhatti** [comment]
Closing as dupe of #16
