### ISSUE TITLE
Deleting Default Web Site Broke Container

### ISSUE THREAD

**Issue by josh-mclean** [microsoft/iis-docker#150]
We tried deleting as well as stopping the default website via a powershell script ran from our dockerfile.

This resulted in errors on the site and we were unable to get the site working.  What is the best practice here?  When using the microsoft/iis image are we required to keep the Default Web Site and put our application on it?  We were able to get the site working by keeping the Default Web Site and moving our site to port 8080.

Thank you
Josh

**Comment by PixelRobots** [comment]
What I do is:

Set up the application pool if needed and then use the below. Thats if you want ssl, you can change the new-website

```
$wwwpath = "sitepath"
$iisObjectName = "sitename"
New-Website -Name $iisObjectName -ApplicationPool $iisObjectName -Force -IPAddress * -PhysicalPath "$wwwpath" -Port 80
Remove-WebSite -Name "Default Web Site"
Start-Website -Name $iisObjectName
```
