### ISSUE TITLE
Application Pools > Advance Settings

### ISSUE THREAD

**Issue by Ramses90** [microsoft/iis-docker#152]
Question: How can I change or set user credentials on a selected application pool. I know how to do it in my local machine but how can I change that without a GUI since IIS image doesn't comes with a GUI

**Comment by bariscaglar** [comment]
You should be able to run PowerShell commands in your dockerfile to add the credentials. Just run the [commands ](https://docs.microsoft.com/en-us/powershell/module/iisadministration/set-iisconfigattributevalue?view=win10-ps) while building your application image. This link is for Set-IISConfigAttributeValue. You can check applicationHost.config file to see what attribute is added. The encryption will be done by the Cmdlet. 

Another way is to do the same change in IIS Manager and checking the script generated. For this, use Configuration Editor to make the change and use the "Generate Script" in the Actions Pane.

Passing build time secrets _safely_ in Dockerfile is a subject that is under constant discussion and I don't know the state of the art. If your dockerfile is open source, this approach clearly won't fly. Even if it isn't, having secrets checked in as plain text is still not a good idea.

The recommended way is to use application pool identities, if you don't need off the machine resource access or managed service accounts if you do so you don't need to deal with credentials.

**Comment by Ramses90** [comment]
Thank you for the recommendations!
