### ISSUE TITLE
Adding Cmd.exe at end of docker image results in IIS terminating

### ISSUE THREAD

**Issue by alburgin** [microsoft/iis-docker#154]
We want to do some run time configuration on container startup.  I have a docker file which consumes the ASP.Net base image and then runs the run time (not build time) configuration using a CMD. (Right now it just does an unzip but later it will do more.)  When I add the line to do the run time configuration, I get the following failures:
"Service 'w3svc' has been stopped

APPCMD failed with error code 4312

Failed to update IIS configuration"

Docker file contents - I have removed some stuff from the docker file which appears to be working: 

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
SHELL ["cmd", "/S", "/C"]
COPY ${source}/ServiceRoot.zip C:/ServiceRoot.zip
#TODO - add more run time config on top of the unzip.
CMD powershell.exe -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('C:\ServiceRoot.zip', 'C:\ServiceRoot'); }"

**Comment by BogdanDamianC** [comment]
similar issue for me I have PS script that executes ServiceMonitor.exe w3svc at the end
For debugging purposes I've replaced the ServiceMonitor.exe w3svc with a long sleep.
Than I logged into the running instance and my site status is "state:Unknown".
If I do an IISreset everything starts working.
But if I do an iis reset immediately after the instance starts I get this error "The system cannot find the file specified. (2147942402, 80070002)" if I wait a little and execute IISReset again it works

**Comment by bestickley** [comment]
I was able to get this working with the start.ps1 script:
```
pm2 start ecosystem.config.js
C:\ServiceMonitor.exe w3svc
```

**Comment by lachlan-vass** [comment]
> Hi, I had the similar issue. I guess it happened because of ServiceMonitor entrypoint in aspnet image. Try to use FROM mcr.microsoft.com/windows/servercore:ltsc2019 instead of aspnet image, then manually isntall net framework and enable web server, so your dockerfile should be like this:
> 
> ```
> FROM mcr.microsoft.com/windows/servercore:ltsc2019
> SHELL ["powershell"]
> 
> RUN Add-WindowsFeature Web-Server; \
>     Add-WindowsFeature NET-Framework-45-ASPNET; \
>     Add-WindowsFeature Web-Asp-Net45
> 
> ADD ./ApplicationBinaries /inetpub/wwwroot
> ADD ./web.config /inetpub/wwwroot/web.config
> 
> COPY AppFirstRun.ps1 .
> 
> CMD ["powershell.exe", "-file C:\AppFirstRun.ps1"]
> 
> RUN Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe" -OutFile "C:\ServiceMonitor.exe"
> 
> CMD ["C:\\ServiceMonitor.exe", "w3svc"]
> ```



> Hi, I had the similar issue. I guess it happened because of ServiceMonitor entrypoint in aspnet image. Try to use FROM mcr.microsoft.com/windows/servercore:ltsc2019 instead of aspnet image, then manually isntall net framework and enable web server, so your dockerfile should be like this:
> 
> ```
> FROM mcr.microsoft.com/windows/servercore:ltsc2019
> SHELL ["powershell"]
> 
> RUN Add-WindowsFeature Web-Server; \
>     Add-WindowsFeature NET-Framework-45-ASPNET; \
>     Add-WindowsFeature Web-Asp-Net45
> 
> ADD ./ApplicationBinaries /inetpub/wwwroot
> ADD ./web.config /inetpub/wwwroot/web.config
> 
> COPY AppFirstRun.ps1 .
> 
> CMD ["powershell.exe", "-file C:\AppFirstRun.ps1"]
> 
> RUN Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe" -OutFile "C:\ServiceMonitor.exe"
> 
> CMD ["C:\\ServiceMonitor.exe", "w3svc"]
> ```

Just want to say @WolfMessing solution worked for me, both locally and running ECS container services. Thank you very much

**Comment by Saibamen** [comment]
> I've been fighting with this for a while i've been unable to get any of the solutions to work until.. Part of my IIS install scrip is removing the default app pool and site. Once I removed this step subbunori's solution works.
> 
> Get-WebSite -Name "Default Web Site" | Remove-WebSite -Confirm:$false -Verbose ; Remove-WebAppPool -Name "DefaultAppPool" -Confirm:$false -Verbose ;


For me, the issue was only for removing web app pool. I can still remove `Remove-WebSite` without any issues.
