### ISSUE TITLE
Anyone get Application Initialization working?

### ISSUE THREAD

**Issue by Tim-Co** [microsoft/iis-docker#156]
Here's my dockerfile set up..

    RUN powershell.exe -NoProfile -Command Add-WindowsFeature Web-AppInit; `
    		Import-Module WebAdministration ; `
    		Set-ItemProperty 'IIS:\AppPools\DefaultAppPool' -name startMode -Value AlwaysRunning ; `
    		Set-ItemProperty 'IIS:\Sites\Default Web Site' -name applicationDefaults.preloadEnabled -Value True ;

Here's my web.config...
```    
<system.webServer>
      <applicationInitialization doAppInitAfterRestart="true" skipManagedModules="false">
        <add initializationPage="/forms/assignmentqueue.aspx" />
      </applicationInitialization>
</system.webServer>
```

I can't get the application initialization to work. Anyone have any luck with this?

**Comment by Cloudmersive** [comment]
This is an important issue.  Why is it not being addressed?

**Comment by bariscaglar** [comment]
@jhkimnew can you take a look?

**Comment by jhkimnew** [comment]
@Tim-Co @sstockhammer 

Did you try to enable IIS FREB for all the status code (200-999) and then check if the configured initializationPage request (/forms/assignmentqueue.aspx) was correctly made with looking at the freb logs?

If you see only IIS log files, you won't be able to see the initializationPage request because IIS does not log them.

**Comment by jhkimnew** [comment]
BTW, here is how to enable IIS Freb tracing on container. 

1. Install IIS Freb with running below command:
Add-WindowsFeature Web-Http-Tracing

2. Enable Freb for Default Web Site with running below command:

Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/sites/site[@name='Default Web Site']/traceFailedRequestsLogging" -name "enabled" -value "True"

3. Configure Freb settings for the web.config of the Default Web Site as the following example:
```
...
        <tracing>
            <traceFailedRequests>
                <add path="*">
                    <traceAreas>
<add provider="ASP" verbosity="Verbose" />
                        <add provider="ASPNET" areas="Infrastructure,Module,Page,AppServices" verbosity="Verbose" />
                        <add provider="ISAPI Extension" verbosity="Verbose" />
                        <add provider="WWW Server" areas="Authentication,Security,Filter,StaticFile,CGI,Compression,Cache,RequestNotifications,Module,FastCGI,WebSocket" verbosity="Verbose" />
                    </traceAreas>
                    <failureDefinitions statusCodes="200-999" />
                </add>
            </traceFailedRequests>
        </tracing>
  </system.webServer>
</configuration>
```
