### ISSUE TITLE
What username/password can be used to access image remotely?

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/iis-docker#16]
Hello,

I can see I can attach to runnning container with Enter-PsSession with "containeruser" account. That account does not seems to be having admin priviliges requried to create another admin account neither can be used for remote managment of server since password is not known.
How exactly you can work with container with UI based tools (Event Viewer, IIS Manager, Computer Manager etc)?

**Comment by mjpearse** [comment]
Have the same (or very similar) question.  
When running images like this or microsoft/nanoserver directly in windows 10, I can't find where the password for the administrator account is documented, and because it is not running in hyper-v as a vhd, I can't get at the nano lite console to set a password.

**Comment by hmdhasani** [comment]
this is my question too
#15

**Comment by mjpearse** [comment]
I figured something out that looks to give me remote powershell as an admin.

From powershell on your host (in my case my windows 10 box which is running some test containers), run:
Enter-PSSession -ContainerId (Get-Container nameofyourrunningcontainer).ID  -RunAsAdministrator

The -ContainerId switch looks to have been added to Enter-PSSession in 5.1.

**Comment by artisticcheese** [comment]
You sure you are admin? Can you try to enable local admininstrator account or something which requires admin privileges.

**Comment by shirhatti** [comment]
It possible to connect to a container as an administrator user and create a local admin account which you can use to connect remotely with IIS Manager. I'll provide more details for the folks who want to try it out but I must caveat this advice since I don't full understand the security implications of doing it this way.

We are also investigating using whether it more secure to use to https://github.com/microsoft/iis.administration as opposed to IIS Manager to remotely.

**Comment by artisticcheese** [comment]
Issue is not just using IIS manager but in general any remote administration tools like event viewer,  server manager etc

**Comment by shirhatti** [comment]
Be sure to expose port 8172 in the container, that is the port that WMSVC listens to by default.

```powershell
PS> docker run -d microsoft/iis
b51e209e2047c3160e7f5fd2700c347082705f874e094b68709d6fb1fff29e6e

PS> docker exec -it b5 powershell
```
```powershell
# Now inside the container
PS C:\> Install-WindowsFeature -Name Web-Mgmt-Service

PS C:\> New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\WebManagement\Server -Name EnableRemoteManagement -Value 1 -Force

EnableRemoteManagement : 1
PSPath                 : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WebManagement\Server
PSParentPath           : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WebManagement
PSChildName            : Server
PSDrive                : HKLM
PSProvider             : Microsoft.PowerShell.Core\Registry

PS C:\> Get-Service -Name WMSVC | Start-Service

PS C:\> net user <username> <password> /ADD

PS C:\> net localgroup administrators <username> /add
```

**Comment by artisticcheese** [comment]
Confirmed that Enter-PSSession -RunAsAdministrator works as well
```

[8f4ae19443e0...]: PS C:\Users\ContainerAdministrator\Documents> Enable-LocalUser Administrator
[8f4ae19443e0...]: PS C:\Users\ContainerAdministrator\Documents> get-localuser

Name           Enabled Description
----           ------- -----------
Administrator  True    Built-in account for administering the computer/domain
```

**Comment by artisticcheese** [comment]
Here is detailed step by step how this works
https://github.com/artisticcheese/artisticcheesecontainer/wiki

**Comment by nathanpovo** [comment]
Not sure what has changed in the 6 years since the solution above was posted, but (to save future readers some time) the solution posted in [this](https://github.com/microsoft/iis-docker/issues/16#issuecomment-265314336) comment does not work.

**Comment by nathanpovo** [comment]
Solution:

Use the following docker file:

```dockerfile
FROM mcr.microsoft.com/windows/servercore/iis

SHELL [ "powershell" ]

#setup Remote IIS management
RUN Install-WindowsFeature Web-Mgmt-Service; \
    New-ItemProperty -Path HKLM:\software\microsoft\WebManagement\Server -Name EnableRemoteManagement -Value 1 -Force; \
    Set-Service -Name wmsvc -StartupType automatic;

#Add user for Remote IIS Manager Login
RUN net user iisadmin Password~1234 /ADD; \
    net localgroup administrators iisadmin /add;
```

Build it: `docker build -t iisremote .`

Run it: `docker run --name remoteiis -d iisremote`

Get the IP address of the container: `docker inspect --format '{{ .NetworkSettings.Networks.nat.IPAddress }}' remoteiis`

Connect to the container using IIS.

Source:
https://devblogs.microsoft.com/premier-developer/iis-remote-management-for-docker-containers/
