### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Juphex** [microsoft/iis-docker#160]
What have you changed in the latest version of the IIS Image? My Services wont work anymore...

**Comment by bariscaglar** [comment]
Month to month releases are for servicing, based on new Windows Image. Perhaps you have some other dependency that has a different behavior. What specific failure are you observing?

**Comment by Juphex** [comment]
net.tcp on localhost (using hosts services)

**Comment by bariscaglar** [comment]
What exactly is happening?

**Comment by Juphex** [comment]
it doesnt connect to the localhost by default anymore. E.g. you could connect to localhost:7377/Service.svc 
It isn't working anymore. I resolved the problem anyway.
