### ISSUE TITLE
I can't download from ubuntu iis image

### ISSUE THREAD

**Issue by sergius76** [microsoft/iis-docker#165]
when i try to make a docker pull mcr.microsoft.com/windows/servercore/iis

show me that Error:
no matching manifest for linux/amd64 in the manifest list entries.

how can i fix it?

I am using docker in ubuntu 19.04

regards

**Comment by bariscaglar** [comment]
IIS is Windows only and can only be used in Windows containers. The manifest you're downloading is a "Manifest List" and it will have no matching entry for your OS.
