### ISSUE TITLE
Can not install Application Request Routing via WebPlatformInstaller

### ISSUE THREAD

**Issue by 16bytes** [Microsoft/iis-docker#17]
After following the instructions for the [Windows 10 Quick Start](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10), I tried to install and configure [ARR](https://www.iis.net/downloads/microsoft/application-request-routing) using the [Web platform tools cmd](https://www.iis.net/learn/install/web-platform-installer/web-platform-installer-v4-command-line-webpicmdexe-rtw-release).

Here is the `Dockerfile` that I'm using:

```
FROM microsoft/iis

RUN powershell -NoProfile -Command \
    Invoke-WebRequest \
    http://download.microsoft.com/download/C/F/F/CFF3A0B8-99D4-41A2-AE1A-496C08BEB904/WebPlatformInstaller_amd64_en-US.msi \
    -Outfile c:\WebPlatformInstaller_amd64_en-US.msi -UseBasicParsing

RUN c:\WebPlatformInstaller_amd64_en-US.msi

RUN mkdir C:\site

RUN powershell -NoProfile -Command \
    Import-module IISAdministration; \
    New-IISSite -Name "Site" -PhysicalPath C:\site -BindingInformation "*:8000:"

EXPOSE 8000

ADD content/ /site
```

But when I try to `WebpiCmd /Install /Products:ARRv3_0 /AcceptEula` in the container, it fails:

```
Starting Installation
Started downloading products...
Started downloading: 'External Cache 1.1'
Downloaded: 'External Cache 1.1'
Started downloading: 'URL Rewrite 2.0'
Downloaded: 'URL Rewrite 2.0'
Started downloading: 'Application Request Routing 3.0'
Downloaded: 'Application Request Routing 3.0'
Started installing Products...
Started installing: 'IIS: WAS Configuration API'
Started installing: '.NET 4.5 Extended with ASP.NET for Windows 8'
Started installing: 'IIS: Management Console'
Install completed (Failure): 'IIS: WAS Configuration API'
WASConfigurationAPI : Failed.

Install completed (Failure): '.NET 4.5 Extended with ASP.NET for Windows 8'
NetFx4Extended-ASPNET45 : Failed.

Install completed (Failure): 'IIS: Management Console'
IISManagementConsole : Failed.

Started installing: 'External Cache 1.1'
Install completed (Success): 'External Cache 1.1'
External Cache 1.1 : Installed
DependencyFailed : URL Rewrite 2.0
DependencyFailed : Application Request Routing 3.0

Verifying successful installation...
IIS: WAS Configuration API                         False
.NET 4.5 Extended with ASP.NET for Windows 8       False
IIS: Management Console                            False
External Cache 1.1                                 True
URL Rewrite 2.0                                    False
Application Request Routing 3.0                    False
Install of Products: FAILURE
```

Can anybody provide troubleshooting suggestions?  There doesn't appear to be anything related in the event log.

Is there a good alternative for using WPI?  That seems to be the strongly recommended way to obtain Application Request Routing, and really, any additional IIS modules.

**Comment by cpunella** [comment]
I have the same issue installing UrlRewrite 2.0... any suggestion?

**Comment by hqer2k9** [comment]
hey there,

to shed some light into the darkness:
starting a powershell process that downloads a *.msi file and executing it afterwards is pretty nice but it wont work the way you want it.

what you wanna do is either one of these two things:
1. use the ADD command from docker to directly download your file (the add command can do this)
and run if afterwards
```
ADD https://download.microsoft.com/download/C/9/E/C9E8180D-4E51-40A6-A9BF-776990D8BCA9/rewrite_amd64.msi /install/rewrite_amd64.msi

RUN msiexec.exe /i c:\install\rewrite_amd64.msi /passive & \
    rd /s /q c:\install
```
**you have to tell the MSI installer to run in passive mode and do not show a UI, because the docker container cant do this**

2. you can manually download the file, then add it to the container and then install it like this:

```
RUN mkdir C:\Site
ADD rewrite_2.0_rtw_x64.msi "C:\Site"
RUN msiexec C:\Site\rewrite_2.0_rtw_x64.msi /quiet /qn /passive
```

hope that helps!

**Comment by 16bytes** [comment]
Thanks for the tips on msi usage @hqer2k9, but it doesn't appear help in the case of using the web platform installer.

The WPI msi does complete successfully, because the `WebpiCmd` is available.

I've also tried to install ARR and its dependencies via MSI using the following instructions:

https://blogs.technet.microsoft.com/erezs_iis_blog/2013/11/27/installing-arr-manually-without-webpi/

In this case, the individual MSIs fail with another error message.  Unfortunately, I don't have the exact error message in this, but IIRC there was something in the event logs that was complaining about the IIS version.

**Comment by tomaszgawlik** [comment]
Is there any reason why Web Platform Installer shouldn't work ?
To eliminate networking problem I've tried using WPI with "offline" mode so: 
locally on my machine: 
`WebPICMD.exe /Offline /Products:ARRv3_0 /Path:c:\OfflineCache`

in dockerfile: 

```
RUN mkdir C:\OfflineCache
ADD /OfflineCache /OfflineCache
RUN powershell -NoProfile -Command \
WebPiCmd.exe /Install /Products:ARRv3_0 /XML:C:\OfflineCache\feeds\latest\webproductlist.xml /Log:platformlog.txt /AcceptEula
```

but still no luck. Log is similar to @16bytes one. 
Did anyone succeeded with this task ?

**Comment by NikitaEgorov** [comment]
https://forums.docker.com/t/iis-url-rewrite-installation/30475/2

```
RUN msiexec /i C:\Site\rewrite_amd64.msi /quiet /qn /passive
```

**Comment by froxplus** [comment]
I have same problem.
this is my docker file:

> FROM microsoft/iis:latest
> SHELL ["powershell"]
> RUN Install-WindowsFeature NET-Framework-45-ASPNET; 
> RUN Install-WindowsFeature Web-Asp-Net45;
> ADD https://download.microsoft.com/download/C/9/E/C9E8180D-4E51-40A6-A9BF-776990D8BCA9/rewrite_amd64.msi /install/rewrite_amd64.msi
> RUN msiexec /i C:\install\rewrite_amd64.msi /quiet /qn /passive
> COPY Deploy Deploy  
> RUN Remove-WebSite -Name 'Default Web Site'  
> RUN New-Website -Name 'test' -Port 80 -PhysicalPath 'C:\Deploy' -ApplicationPool '.NET v4.5'
> EXPOSE 80

after running docker with this image i'll get http 500 error that belongs to url_rewirte module
but if after creating a container run:
`docker exec frox msiexec /i C:\install\rewrite_amd64.msi /quiet /qn /passive`
it will work fine.
any solution for this problem?

**Comment by froxplus** [comment]
my problem solved
i just replaced
`RUN msiexec /i C:\install\rewrite_amd64.msi /quiet /qn /passive`
to
`RUN Start-Process 'C:\install\rewrite_amd64.msi' '/qn' -PassThru | Wait-Process;
`

**Comment by shirhatti** [comment]
@16bytes ARR Dockerfile- https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/windows-container-samples/iis-arr/Dockerfile

Looks like this issue was resolved, however I do understand the concern expressed.
I have created an uber issue to create some guidance around install IIS OOBs in containers- https://github.com/Microsoft/iis-docker/issues/48
