### ISSUE TITLE
Problems with Install-WindowsFeature

### ISSUE THREAD

**Issue by Fufe1ok** [microsoft/iis-docker#172]
I am tring to deploy .net framework application in IIS container. But i need to install  Web-Asp-Net45, and all worked fine in my laptop, but when i tried to make the same on build server ( Windows Server 2016) it failed, and i can not find the solution. 
![image](https://user-images.githubusercontent.com/32967290/77455863-1553eb80-6e03-11ea-94a9-83706dea27b4.png)
 When i tried to make the same using DISM i encouneterd with the same error code ` 0x800f0922`
Also i have problems with choco installing on it, but it is not so important
Does anyone have ideas about how to solve it?

**Comment by Ankit3794** [comment]
@Fufe1ok  Which base image you are using for windows server 2016?

**Comment by Fufe1ok** [comment]
> 
> 
> @Fufe1ok Which base image you are using for windows server 2016?

I try to use several images, currently i use image, whuch was pulled, just using `docker pull microsoft/iis` but also i had same problem on `mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2016` image

**Comment by Ankit3794** [comment]
@Fufe1ok Can you try with this image `docker pull mcr.microsoft.com/dotnet/framework/aspnet` this image? 

That image includes 

- Windows Server Core as the base OS
- IIS 10 as Web Server
- .NET Framework (multiple versions available)
- .NET Extensibility for IIS

**Comment by Fufe1ok** [comment]
> 
> 
> @Fufe1ok Can you try with this image `docker pull mcr.microsoft.com/dotnet/framework/aspnet` this image?
> 
> That image includes
> 
>     * Windows Server Core as the base OS
> 
>     * IIS 10 as Web Server
> 
>     * .NET Framework (multiple versions available)
> 
>     * .NET Extensibility for IIS

@Ankit3794 thank you a lot, it work))

**Comment by jhkimnew** [comment]
Hi @Ankit3794, this is a known issue. Probably this will be fixed in the next build. 

https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t

FYI, the workaround of this known issue is to match the host’s version with the container’s version.
