### ISSUE TITLE
Image fails to run with gmsa account using --security-opt "credentialspec=" option

### ISSUE THREAD

**Issue by undecided2013** [microsoft/iis-docker#175]
Using command
docker run --security-opt "credentialspec=file://testgmsa.json" --hostname gmsaWeb -it microsoft/iis powershell
The image returns
Service 'w3svc' has been stopped

APPCMD failed with error code 4312

Failed to update IIS configuration

Same command but targeting ltsc2019 works:

docker run --security-opt "credentialspec=file://testgmsa.json" --hostname gmsaWeb -it mcr.microsoft.com/windows/servercore:ltsc2019 powershell

I am suspicious of ServiceMonitor Entrypoint not handling the security-opt parameter correctly.

I posted same error in other places such as:

https://github.com/microsoft/dotnet-framework-docker/issues/607
https://github.com/microsoft/IIS.ServiceMonitor/issues/70

Have not seen any activity. This is a huge showstopper for migrating legacy asp.net sites/apps to docker containers.

**Comment by jkrnl** [comment]
Any update on this?
