### ISSUE TITLE
Environment variables not set if call early

### ISSUE THREAD

**Issue by iskiselev** [microsoft/iis-docker#176]
Due to microsoft/IIS.ServiceMonitor#74, if web call will reach IIS before ServiceMonitor updates environment variables, they will not be updated in affected app pool. As an workaround for this in docker file IIS service may be started manually - it will be started by ServiceMonitor in that case.

**Comment by shirhatti** [comment]
This is a known limitation. Unfortunately, we cannot change the base image to have was/w3svc stopped by default. This would be breaking especially since we're aware a large number of customers override the entry point.

The simple workaround would be to add `net stop /y was` to your Dockerfile
