### ISSUE TITLE
"verify in the browser" wrong instructions

### ISSUE THREAD

**Issue by MassimilianoCuccia** [microsoft/iis-docker#179]
**to verify in the browser open the url htp://YOURIP:8000 or whatever port you used**

the ip returned by
docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" my-running-site
doesn't work

Please correct the guide

**Comment by John-Hart** [comment]
thanks @MassimilianoCuccia, we'll look into fixing this
