### ISSUE TITLE
IIS Servicemonitor crashes when %18 is used in environment variable

### ISSUE THREAD

**Issue by erenes** [microsoft/iis-docker#188]
The IIS servicemonitor and therefore our containers crash if the environment variable contain a %## sequence that resolve to an invalid XML character when URL encoded. 

Steps to reproduce: 
1. `docker run -p80:80 -e TEST="%18" mcr.microsoft.com/windows/servercore/iis`

**Expected:** Image runs and I can access an IIS test page on http://localhost
**Actual:** Image runs and immediately crashes.
```
PS C:\Temp\docker\iis> docker run -p80:80 -e TEST="%18" mcr.microsoft.com/windows/servercore/iis

 Service 'w3svc' has been stopped

APPCMD failed with error code -1072894421

Failed to update IIS configuration
```

Suggested fix: 
Update the IIS Monitor with this PR: https://github.com/microsoft/IIS.ServiceMonitor/pull/72

Previously reported in August 2020: 
https://github.com/microsoft/IIS.ServiceMonitor/issues/71

**Comment by erenes** [comment]
Hi and thanks for looking into the issue!

Since it was marked complete, I thought I would try again with my current laptop, but it appears that the problem has not been resolved in the released version of the image: 
```
❯ docker run -p8000:80 -e TEST="%18" mcr.microsoft.com/windows/servercore/iis

Stopping service 'w3svc'

 Service 'w3svc' has been stopped

APPCMD failed with error code -1072894421

Failed to update IIS configuration
```

Assuming that this was not closed by mistake, is there an ETA for the update version of the image to be released?

**Comment by John-Hart** [comment]
This was closed as part of a bulk cleanup of very old issues to get to a manageable state. It was not fixed.  If you feel this issue is still a blocking issue please feel free to open a new issue and we can prioritize it.
