### ISSUE TITLE
Binding site with current domain

### ISSUE THREAD

**Issue by petrck** [Microsoft/iis-docker#19]
Hi, I apologize, for maybe stupid question, but I'm not sure if I understand how to bind my new site, with production domain. If I create new site and register port with IP address my server, everything works well (for example: http://1.1.1.1). But how can I say, my site demo, on address server 1.1.1.1 will be accessible at www.mydemo.com. IIS without docker can solve this. Is it possible do this with this Image? Thank you.

**Comment by shirhatti** [comment]
You can use IIS-Administration PowerShell cmdlets or use `appcmd` to create a new binding.

Here's how to create a new binding in PowerShell
````powershell
$sm = Get-IISServerManager
$sm.Sites["Default Web Site"].Bindings.Add("*:80:bar.com", "http")
$sm.CommitChanges()
````
Additionally, I'd recommend looking at [Jeong Hwan's blog on using PowerShell to configure IIS](https://blogs.iis.net/jeonghwan/how-to-use-iisadministration-powershell-cmdlets-to-configure-iis-configuration-settings).

Feel free to reopen if you are still having difficulties.
