### ISSUE TITLE
I would like to deploy this to ServiceFabric

### ISSUE THREAD

**Issue by ryaker** [Microsoft/iis-docker#20]
I would like to deploy this to ServiceFabric. The deploy works, but I can't seem to figure out how to configure correctly to hit IIS running on port 80 in the container. Being able to create containers with our legacy web apps, and WCF services and deploy to ServiceFabric will be a game changer here.  Any help would be appreciated.

**Comment by shirhatti** [comment]
@glennc Do you know who can help with ServiceFabric?

**Comment by shirhatti** [comment]
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-container

**Comment by shirhatti** [comment]
Feel free to re-open if you have issues
