### ISSUE TITLE
Is this repository active?

### ISSUE THREAD

**Issue by GaTechThomas** [microsoft/iis-docker#203]
Many questions are lying unanswered. We need help please. If this repository is dead then please indicate so in the main readme. Thank you.

**Comment by GaTechThomas** [comment]
I've spent more hours than I care to count trying to get this image running on Windows 10, the primary problem was that the `pull` failed. After MUCH spinning on suggestion after suggestion from the web, I tried enabling every Windows feature that is remotely related to containers or Hyper-V, and one of those allowed the pull to occur. Now I'm at the point at which I need to administer IIS in the container, but installing tool after tool, feature after feature (even the full RSAT) still gives no option for remote management of IIS. Most everything seems to have been built for Windows Server and therefore the guidance is thin on doing so on desktop versions of WIndows.

I describe all the above because this repository IS the place where all that info should be available. But the repository has so little activity that it's pretty clear that spending time here and attempting to use this image is not helpful. Please prove me wrong - until then, I'm moving on. Thank you.

**Comment by John-Hart** [comment]
yes this is still active
