### ISSUE TITLE
It doesn't work after I installed hosting bundle 8.0.1, the application show error: Could not find dotnet.exe at 'c:\inetpub\wwwroot\api\dotnet' or using the system PATH environment variable.

### ISSUE THREAD

**Issue by mma-alterdomus** [microsoft/iis-docker#204]
It doesn't work after I installed hosting bundle 8.0.1, the application show error: Could not find dotnet.exe at 'c:\inetpub\wwwroot\api\dotnet' or using the system PATH environment variable.

BTW, it work good for hosting bundle 6.

My dockerfile is as bellow:

        FROM mcr.microsoft.com/windows/servercore/iis AS final
        SHELL ["powershell"]
        EXPOSE 80 443

        RUN Invoke-WebRequest http://download.microsoft.com/download/D/D/E/DDE57C26-C62C-4C59-A1BB-31D58B36ADA2/rewrite_amd64_en-US.msi -OutFile "c:/rewrite_amd64_en-US.msi"
        RUN Start-Process -FilePath "c:/rewrite_amd64_en-US.msi" -ArgumentList "/qn" -Wait

        RUN Invoke-WebRequest 'https://download.visualstudio.microsoft.com/download/pr/016c6447-764a-4210-a260-bf7a2880d5c0/a5746437a3862d7803284ae8c2290200/dotnet-hosting-8.0.1-win.exe' -UserAgent '' -OutFile "C:/dotnet-hosting.exe"
        RUN Start-Process -FilePath "c:/dotnet-hosting.exe" -ArgumentList @('/install', '/q', '/norestart', 'OPT_NO_RUNTIME=1', 'OPT_NO_SHAREDFX=1') -Wait -PassThru

        # Copy the build artifacts
        ADD aaa /inetpub/wwwroot
        ADD bbb/s /inetpub/wwwroot/api/Rules

        # Create the Web Applications, use different application pool for each, mix hosting mode is not supported
        RUN New-WebAppPool -Name "AppPoolAPI"
        RUN New-WebApplication -Name api -Site 'Default Web Site' -PhysicalPath "c:\inetpub\wwwroot\api" -ApplicationPool AppPoolAPI

        RUN New-WebAppPool -Name "AppPoolSSO"
        RUN New-WebApplication -Name SSO -Site 'Default Web Site' -PhysicalPath "c:\inetpub\wwwroot\sso" -ApplicationPool AppPoolSSO

**Comment by John-Hart** [comment]
I recommend opening an issue with dotnet:  https://github.com/microsoft/dotnet-framework-docker/issues/new/choose

**Comment by mma-alterdomus** [comment]
Thanks for your suggestion. We have changed our containers into Linux based now.
