### ISSUE TITLE
Run IIS using Docker on AWS

### ISSUE THREAD

**Issue by mado-bohsali** [microsoft/iis-docker#208]
I am not able to Dockerize my ASP.NET core using my Mac OS machine. I am using the latest base image you provided:

FROM mcr.microsoft.com/windows/servercore:ltsc2022

OR

FROM mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2022

**Error: error: failed to solve: failed to register layer: link /files/program files/common files/system/ado/en-us/msader15.dll.mui /files/program files (x86)/common files/system/ado/en-us/msader15.dll.mui: no such file or directory**

**Error: ERROR: failed to solve: mcr.microsoft.com/windows/servercore:ltsc2022: failed to resolve source metadata for mcr.microsoft.com/windows/servercore:ltsc2022: no match for platform in manifest: not found**

**Comment by erenes** [comment]
As far as I know you can't use windows docker images on MacOS (unless you're running a windows VM I suppose), have you tried using:
`mcr.microsoft.com/dotnet/aspnet:8.0` as base image? 

See also: 
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-8.0
