### ISSUE TITLE
WebFarm Framework installed but cant create WebFarm

### ISSUE THREAD

**Issue by hqer2k9** [Microsoft/iis-docker#22]
Installed the newest WebFarm Framework successfully on the Docker Container, but cant create a WebFarm since the option to do this is missing. (Server-Farm not showing)

am i missing something?

**Comment by shirhatti** [comment]
@pan-wang Any ideas why this might be happening?

**Comment by pan-wang** [comment]
@hqer2k9 could you please provide more information about the version WebFarm Framework and How the container was set up? What's the error you hit? Just for your reference, we recommend ARR https://www.iis.net/downloads/microsoft/application-request-routing for web farm scenario.

**Comment by shirhatti** [comment]
@hqer2k9 Closing issue since it's stale. Feel free to re-open if this issue persists
