### ISSUE TITLE
MSI Packages are not getting installed (no negative docker feedback)

### ISSUE THREAD

**Issue by hqer2k9** [Microsoft/iis-docker#23]
When installing MSI packages, i noticed that it builds successfully, but packages are not installed. There is no error message or other stuff coming up.

2 Methods that i use:

**1.  Method:**
```
ADD HTTPLINKTOFILE/MSIFILE.msi /folder/MSIFILE.MSI
RUN msiexec.exe /i C:\folder\MSIFILE.MSI /passive & \
rd /s /q C:\Folder
```

**2. Method:**
```
ADD MSIFILE.msi "C:\Folder\"
RUN msiexec.exe C:\folder\MSIFILE.MSI /quiet /qn /passive
```

The http link method successfully installs the MSI file without returning any error.
But it does not show up, installed URL REWRITE or ARR or any other stuff but it's just not there.

The second method via adding the file to the Docker Volume and then installing it makes the DOCKER BUILD process hang, it just stays there without going any further, also no error message.

Sad i cant deliver a stack trace or error message but that's all i got. Anyone knows how to handle that?
This is not a duplicate to other MSI related issues since here, it get's installed in the first place but won't show functionality.

**Comment by technocrat000** [comment]
I have the same problem with docker 17.03.1-ee-3, build 3fcee33  on Windows Server 2016.  I used 2-nd method from hqer2k9's post.  docker build just hangs at RUN step

**Comment by artisticcheese** [comment]
You need to use Start-Process with -Wait flag for those

**Comment by shirhatti** [comment]
@hqer2k9 If this issue still persists feel free to re-open with a repro.
