### ISSUE TITLE
windowsservercore images not available. Please repost to dockerhub

### ISSUE THREAD

**Issue by rs2** [Microsoft/iis-docker#26]
```
docker pull microsoft/windowsservercore

Using default tag: latest
latest: Pulling from microsoft/windowsservercore
3889bb8d808b: Retrying in 1 second
3430754e4d17: Retrying in 10 seconds
```

**Comment by zaxfenfeiyu** [comment]
+1

**Comment by shirhatti** [comment]
I suspect your version of the docker CLI is out of date. Try updating docker and try again.
If you are still having difficulties, please share the output of `docker version`.

**Comment by rs2** [comment]
@shirhatti You are correct. 
1. `docker-machine upgrade default`
2. profit

**Comment by Rakaim** [comment]
Same error with a build I downloaded today:

Docker version 18.06.0-ce, build 0ffa825

Even the first layer matches hashes.

![image](https://user-images.githubusercontent.com/23176626/43679136-89bbf198-97e5-11e8-9b67-2126685f81f8.png)

Using Windows Server Core so while I'm new to Windows Docker fun, I'm *fairly confident* that the command `docker-machine upgrade default` doesn't apply here.
