### ISSUE TITLE
the operation timed out... (containers on windows 10)

### ISSUE THREAD

**Issue by wxb1** [Microsoft/iis-docker#27]
C:\WINDOWS\system32>docker run -it microsoft/iis cmd
docker: Error response from daemon: container dd196647758cf92828efd44934cb4862b4117dc4a556b20c5de8ee54c0b59d33 encountered an error during Start: failure in a Windows system call: The operation timed out because a response was not received from the Virtual Machine hosting the Container. (0xc0370109).

**Comment by shirhatti** [comment]
@patricklang Do you know how to diagnose this problem?

**Comment by ratebeerjoet** [comment]
Were you able to fix this?

**Comment by PatrickLang** [comment]
I haven't been able to reproduce it. Does `docker run -it Microsoft/nanoserver` succeed?

Also try the scripts here:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting

**Comment by ratebeerjoet** [comment]
@PatrickLang I'm testing this right now. docker insisted on "microsoft" in lower case, syntactically. I'll feed back shortly.

**Comment by ratebeerjoet** [comment]
It worked! Thanks

**Comment by PatrickLang** [comment]
what about `microsoft/windowsservercore` ?

**Comment by PatrickLang** [comment]
@ratebeerjoet sorry about the caps. Docker does insist on lowercase but my browser autocorrects. Grrr

**Comment by IanCodeGG** [comment]
I have seen this before, when running within VMWare Fusion with insufficient resources allocated.

**Comment by shirhatti** [comment]
Feel free to re-open if the issue still persists

**Comment by wxb1** [comment]
I believe IanGSY is correct in my case. I got VMware services running in the background and the computer in question was low on resources. I switched to another computer which was beefer and I did not have a problem. I plan on adding memory to the computer with the issue. If I am still having the problem then I will reopen the issue.

**Comment by satyapal88** [comment]
I am facing the same issue. For me this is random issue. First time it was working fine for me. After that I just  removed the container and try to create it again. But I am getting the same issue-


Error response from daemon: container 60fef2228d62a8337d7e41d92acbf1305998e351df04704d056667dc26234b66 encountered an error during Start: failure in a Windows system call: The operation timed out because a response was not received from the Virtual Machine hosting the Container. (0xc0370109).

**Comment by shirhatti** [comment]
@satyapal88 Have you tried https://docs.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting

cc @PatrickLang

**Comment by wxb1** [comment]
How do I open this back up?

**Comment by wxb1** [comment]
I added more ram but I am still having issues.

I can create containers from the "nano" based images but not from the others.

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd\

C:\>docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
microsoft/aspnet              latest              4f50b9345689        4 weeks ago         -1 B
microsoft/aspnet              3.5                 cfcdb5a163e1        4 weeks ago         -1 B
sqnwebservice                 latest              58c2edbe4195        6 months ago        -1 B
nanoserver/iis                latest              6fc13fccd923        6 months ago        -1 B
microsoft/aspnet              <none>              e761eca2f8df        7 months ago        -1 B
microsoft/iis                 latest              a3dd2dff392b        7 months ago        -1 B
helloworld                    latest              8bc11b0b385e        7 months ago        -1 B
microsoft/windowsservercore   10.0.14393.693      4d83c32ad497        8 months ago        -1 B
microsoft/windowsservercore   latest              4d83c32ad497        8 months ago        -1 B
microsoft/nanoserver          latest              d9bccb9d4cac        8 months ago        -1 B

C:\>
C:\>docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
microsoft/aspnet              latest              4f50b9345689        4 weeks ago         -1 B

**Comment by wxb1** [comment]
Here is my troubleshooting log... If you notice anything please let me know.  I would love to get docker  running on this machine as it will be my main machine going forward...

Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 3.64s
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 584ms
 [+] Is not a build with blocking issues 119ms
 [+] Has 'Containers' feature installed 53.35s
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  485ms
 [+] Service is running 90ms
 [+] Docker.exe is in path 3.33s
 [+] Docker is registered in the EventLog service 118ms
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 185ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set to 1 204ms
 [+] Do not have zz values set 222ms
 [+] Do not have FDVDenyWriteAccess set to 1 115ms
Describing The right container base images are installed
 [+] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 519ms
Describing Container network is created
 [+] At least one local container network is available 11.75s
 [+] At least one NAT, Transparent, or L2Bridge Network exists 122ms
 [+] NAT Network's vSwitch is internal 85ms
 [+] A Windows NAT is configured if a Docker NAT network exists 1.47s
 [+] Specified Network Gateway IP for NAT network is assigned to Host vNIC 961ms
 [+] NAT Network's internal prefix does not overlap with external IP' 149ms
Showing output from: docker info
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 9
Server Version: 1.13.0-rc4
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Security Options:
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 7.894 GiB
Name: DESKTOP-RM4F0E2
ID: CCKN:RCF7:T3UO:OINV:M2CH:RLYS:KSE5:VQ55:B26H:5BG5:UPYF:I7FY
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

Showing output from: docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      windows/amd64

Showing output from: docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
afb51c1a4585        nat                 nat                 local
c46eb8e22351        none                null                local

Getting Warnings & errors in the Windows event logs from the last 24 hours


   ProviderName: docker

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
9/9/2017 8:18:14 AM              1 Error            Handler for POST /v1.24/containers/1e4a2e3ed998f92521c20e9227aa4...
9/9/2017 8:18:13 AM              1 Error            Create container failed with error: container 1e4a2e3ed998f92521...
9/9/2017 8:18:13 AM              1 Error            libcontainerd: failed to start container: container 1e4a2e3ed998...


   ProviderName: Microsoft-Windows-Hyper-V-Compute

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
9/9/2017 8:15:55 AM          12003 Warning          Cannot create a template for a Hyper-V Container, reached the ma...

**Comment by anwar0206** [comment]
Hi !,
Did anyone able to resolve this issue.

I created the cotainner, it worled perfectly fine for the whole day. Shutdown the Laptop which is Windows 10 Anniversary Update. Next day... containner not startring.

**Comment by mrichman** [comment]
I'm stuck too:

```
[15:46:15.010][WindowsDaemon  ][Info   ] debug: HCSShim::CreateContainer succeeded id=8031ec0819ba713c3b0d6a8153964bc5207cfa03e07a298d7502cb85d6a8af9c handle=122104240
[15:46:15.010][WindowsDaemon  ][Info   ] debug: libcontainerd: createWindows() id=8031ec0819ba713c3b0d6a8153964bc5207cfa03e07a298d7502cb85d6a8af9c, Calling start()
[15:46:15.011][WindowsDaemon  ][Info   ] debug: libcontainerd: starting container  8031ec0819ba713c3b0d6a8153964bc5207cfa03e07a298d7502cb85d6a8af9c
[15:46:15.011][WindowsDaemon  ][Info   ] debug: HCSShim::Container::Start id=8031ec0819ba713c3b0d6a8153964bc5207cfa03e07a298d7502cb85d6a8af9c
[15:47:16.951][WindowsDaemon  ][Info   ] debug: Result: {"Error":-1070137079,"ErrorMessage":"The operation timed out because a response was not received from the Virtual Machine hosting the Container."}
[15:47:16.951][WindowsDaemon  ][Error  ] libcontainerd: failed to start container: container 8031ec0819ba713c3b0d6a8153964bc5207cfa03e07a298d7502cb85d6a8af9c encountered an error during Start: failure in a Windows system call: The operation timed out because a response was not received from the Virtual Machine hosting the Container. (0xc0370109)
[15:47:16.953][WindowsDaemon  ][Info   ] debug: HCSShim::Container::Terminate id=8031ec0819ba713c3b0d6a8153964bc5207cfa03e07a298d7502cb85d6a8af9c
[15:47:16.957][WindowsDaemon  ][Info   ] debug: libcontainerd: cleaned up after failed Start by calling Terminate
```
