### ISSUE TITLE
manifest for microsoft/iis:nanoserver not found

### ISSUE THREAD

**Issue by kristian-b** [Microsoft/iis-docker#29]
Hello,

If I try to pull the microsoft/iis:nanoserver image (`docker pull microsoft/iis:nanoserver`), I get the following error:
`Error response from daemon: manifest for microsoft/iis:nanoserver not found`

What am I doing wrong?

My environment:
- Windows 10 Pro 14393.693
- Docker 1.13.1 (10072)

**Comment by shirhatti** [comment]
I'm guessing it had to with the [Docker Registry outage today morning](https://twitter.com/dockerstatus/status/836635110539575296).
Feel free to re-open if your issue persists.

**Comment by kristian-b** [comment]
Thank you, now it works. :)
