### ISSUE TITLE
Publish NanoServer images

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/iis-docker#3]

**Comment by shhsu** [comment]
Done

**Comment by jabbera** [comment]
While the image itself is useful is there a list of all the other cab components available for download and their locations? https://az880830.vo.msecnd.net/nanoserver-ga-2016/ isn't browsable.

https://github.com/Microsoft/iis-docker/blob/shhsu/nano/nanoserver/Dockerfile
 
Thanks!
Mike

**Comment by shhsu** [comment]
Try these

https://nanoserverpackage.blob.core.windows.net/nanoserver-ga-2016/searchNanoServerIndex.txt
