### ISSUE TITLE
Where is the source for ServiceMonitor.exe?

### ISSUE THREAD

**Issue by richlander** [Microsoft/iis-docker#31]
It should either be available or an attribution of where it comes from.

**Comment by cdhunt** [comment]
I created an open-sourced my own version of Service Monitor. It also will tail a log file and pipe it to stdout to funnel events through Docker logging drivers.
https://github.com/Ticketmaster/spinner

**Comment by funky81** [comment]
@cdhunt thanks for the spinner apps. I just re-built my on docker image for iis based dockerfile.
This time I use spinner. Anyway, are you hosting at github for the source code? or libraries.io?

**Comment by richlander** [comment]
Can you make the source available, @shirhatti?

**Comment by cdhunt** [comment]
@funky81, Source and Binaries are GitHub.

**Comment by richlander** [comment]
Hey @cdhunt ... your spinner service looks cool. Would be great to learn more about what you are doing. Care to chat? Mail me at rlander@ms.

**Comment by shirhatti** [comment]
See https://github.com/Microsoft/IIS.ServiceMonitor
