### ISSUE TITLE
How may I access the web application from remote?

### ISSUE THREAD

**Issue by Geekays** [Microsoft/iis-docker#32]
The docker IIS documentation says:

> With the current release, you can't use http://localhost to browse your site from the container host. This is because of a known behavior in WinNAT, and will be resolved in future. Until that is addressed, you need to use the IP address of the container.

So, what is the way out to be able to publish a web application to the internet using Docker? I just tried publishing my web application. I could create docker image, publish and run it on a VM on Azure. However, I am not finding a way to share this with anyone as the web application is not available on the IP of the VM.

Can someone help me?

**Comment by shirhatti** [comment]
> I just tried publishing my web application. I could create docker image, publish and run it on a VM on Azure. However, I am not finding a way to share this with anyone as the web application is not available on the IP of the VM.

I'm sorry the description of the WinNAT limitation was a little brief. I'd recommend reading [this WinNAT blog post](https://blogs.technet.microsoft.com/virtualization/2016/05/25/windows-nat-winnat-capabilities-and-limitations/) and especially have a look at the `Accessing internal endpoints directly from the Host` section.

If I had to guess what's wrong in your setup, I suspect the network security group for your VM doesn't allow access to the mapped port on the container host.

**Comment by Geekays** [comment]
Thanks.

However, what is elaborated in the section 

> Accessing internal endpoints directly from the Host

 in the blog, still does not answer how an end user can access the application from internet. 

Let us refer to the section:

> The one caveat to this limitation is that the internal endpoint can be accessed using the external IP/port from a separate, VM/container endpoint running on the same NAT host: this is called hair-pinning. E.g. A user operating on container A can access a web server running in Container B using the internal IP and port of http://10.10.50.20:8080.


So, does it mean I can access the application using the hosts IP/port from another VM that shares the same NAT host? What happens to someone who wish to access it from a different location (for me outside Azure) and need to access?

I'm sorry if I am asking stupid questions, but my networking knowledge is limited.

**Comment by shirhatti** [comment]
Let's say you create a container on your host and set up a port mapping, `docker run -d -p 8080:80 microsoft/iis`
Your service running on port 80 inside the container will be accessible externally at `http://public-ip-of-container-host:8080`


> If I had to guess what's wrong in your setup, I suspect the network security group for your VM doesn't allow access to the mapped port on the container host.

Adding to my previous suggestion. Make sure the network security group of you Azure VM allows access to port 8080 (in this example) on the container host.

**Comment by Geekays** [comment]
Thanks. NSG was holding me back!
