### ISSUE TITLE
.NET Core Windows Server Hosting bundle

### ISSUE THREAD

**Issue by thepill** [Microsoft/iis-docker#33]
The asp.net documentation https://docs.microsoft.com/en-us/aspnet/core/publishing/iis mentions that the .NET Core Windows Server Hosting bundle is needed to run a ASP.NET core application.

When trying to install the bundle via msiexe following error occures:

```
T h i s   i n s t a l l a t i o n   p a c k a g e   c o u l d   n o t   b e   o p e n e d .     C o n t a c t   t h e   a p p l i c at i o n   v e n d o r   t o   v e r i f y   t h a t   t h i s   i s   a   v a l i d   W i n d o w s   I n s t a l l e r   p a c k a g
e .
```

**Comment by shirhatti** [comment]
The server hosting bundle in an exe and not an msi.

Try running `.\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe /quiet /install`.

**Comment by thepill** [comment]
this isn´t working when used in the Dockerfile like this `RUN .\DotNetCore.exe /quiet /install`.

If i exec into the container and run it `RUN .\DotNetCore.exe /quiet` it is working

Dockerfile:

```
FROM microsoft/iis
SHELL ["powershell"]

RUN Install-WindowsFeature NET-Framework-45-ASPNET ; \  
    Install-WindowsFeature Web-Asp-Net45

COPY DotNetCore.exe .
RUN .\DotNetCore.exe /quiet
COPY GroupManagedServiceAccountASPNET/bin/Release/PublishOutput test  
RUN Remove-WebSite -Name 'Default Web Site'  
RUN New-Website -Name 'test' -Port 80 \  
    -PhysicalPath 'c:\test' -ApplicationPool '.NET v4.5'
EXPOSE 80
```

**Comment by thepill** [comment]
if i place the command `RUN .\DotNetCore.exe /quiet /install`on the second last line before `EXPOSE 80` it works. Seems like something is overwriting the filesystem. Is this normal?

**Comment by shirhatti** [comment]
I'm not observing the same behavior. Can you share your installer logs from inside the container so I can further investigate?

I need the content of all these files `Get-ChildItem -Filter "*Core*.log" -Path $env:temp`

**Comment by thepill** [comment]
I really don´t know why - but it is no working each time...
closing this - thank you @shirhatti

**Comment by thepill** [comment]
@shirhatti i stumbled over this problem once more and thought about including this in this base image. Is this reasonable?

**Comment by shirhatti** [comment]
Unfortunately, no. The iis base image is used for workloads other just ASP.NET Core.
If there's enough demand, we can consider publishing an ASP.NET Core image with IIS and the Server Hosting bundle. However, we have no plans at the moment

**Comment by AlexandreOuellet** [comment]
an iis + aspnetcore image would be quite useful, as I am also struggling to get this working (our webapp can use many different authentication, Windows Authentication being one of them, and is not available under linux yet)

**Comment by thepill** [comment]
@AlexandreOuellet i managed to run aspnetcore (net461) + iis running on docker on windows using a gMSA (group managed service account) to authenticate to Active Directory (using Directory Services to obtain some information from the AD)

**Comment by wweeder** [comment]
I am also struggling trying to run a aspnetcore app with iis which seems to require the '.NET Core Windows Server Hosting'. @thepill @shirhatti can you please share any Dockerfile that demonstrates how to do this?

**Comment by thepill** [comment]
@wweeder this is my base image:

```
# escape=`
FROM microsoft/aspnet:4.7.1-windowsservercore-ltsc2016
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

COPY DotNetCore.2.0.3-WindowsHosting.exe .

RUN ./DotNetCore.2.0.3-WindowsHosting.exe /quiet /install

RUN Import-Module WebAdministration; `
    New-Item "IIS:\AppPools\App"; `
    Set-ItemProperty "IIS:\AppPools\App" -Name processModel.idleTimeout -value ([TimeSpan]::FromMinutes(0)); `
	Set-ItemProperty "IIS:\AppPools\App" -Name managedRuntimeVersion -value '';

RUN Remove-WebSite -Name 'Default Web Site'; ` 
    New-Item -Path 'C:\app' -Type Directory; `
    New-Website -Name 'Application' -Port 80 -PhysicalPath 'c:\app' -ApplicationPool 'App'

EXPOSE 80
```

Notice that you have to download the `NET Core Windows Server Hosting` and put it in the same file as the dockerfile. I also tried to download the newest verstion within the dockerfile but this didnt work every time...

**Comment by wweeder** [comment]
@thepill tyvm!
