### ISSUE TITLE
Will this run classic ASP?

### ISSUE THREAD

**Issue by mnishizawa** [Microsoft/iis-docker#34]
I have a classic ASP site I'd like to test locally.

**Comment by gregpakes** [comment]
Yes - You just need to install the role.

```
RUN Enable-WindowsOptionalFeature -FeatureName "IIS-ASP" -Online -All -NoRestart;
```

**Comment by shirhatti** [comment]
Feel free to re-open if you have additional questions

**Comment by FushenYang** [comment]
I get what i want,thank you.
