### ISSUE TITLE
Can I allow IIS to output detailed errors in a container running an MVC project? I only get static "Internal Server Error" without any information.

### ISSUE THREAD

**Issue by KevinVording** [Microsoft/iis-docker#35]
Pretty much as the title says. 

As part of my internship its my job to find out if Docker is a valid solution for the company. 

I have some projects that run inside a container perfectly fine after fiddling with the settings and or dockerfile, but I've been stuck for 2 weeks on one particular project right now. Every http error is the same in the sense there is no information at all where the error originates from. 

All projects have the tags for errorMode=Detailed and customErrors=off in the webconfig. The traditional debugger in visual studio will give me detailed errors, but when dockerized it will give me absolutely nothing. 

Thanks in advance!

**Comment by shirhatti** [comment]
By default, IIS hides detailed error pages for remote connections. You can always enable them from your `web.config`

```xml
<configuration>
  <system.web>
    <customErrors mode="Off" />
  </system.web>

  <system.webServer>
    <httpErrors errorMode="Detailed" />
  </system.webServer>
</configuration>
```

Word of **caution** though, detailed error pages can leak implementation details about your site, it is a security vulnerability to flow this information to the end user.

**Comment by shirhatti** [comment]
Feel free to re-open if you continue to have issues.

**Comment by KevinVording** [comment]
In my post I stated that the project contains both those elements, but IIS in docker does nothing with that information in the web.config.

I managed to remote login onto the containerized IIS server and found out I had to set it to detailed in IIS itself. I found out what my problem was, a module in IIS that's not installed by default called a "Rewrite Module" for URL rewrites.

However now I am having the issue: **Filename: redirection.config Error: Cannot read configuration file due to insufficient permissions** 

Any knowledge on this?

**Comment by Gudagapu** [comment]
I am unable to find web.config on my windows machine.

![image](https://user-images.githubusercontent.com/37993464/38183305-137045b4-365d-11e8-9400-45daf38c8cf1.png)

**Comment by kbdavis07** [comment]
How did you edit the Web.config file on the host? @KevinVording

**Comment by Cloudmersive** [comment]
No reply on this?

**Comment by KevinVording** [comment]
> How did you edit the Web.config file on the host? @KevinVording
> 
> **Currently I am getting this:**
> 
> ![image](https://user-images.githubusercontent.com/5434970/43380410-13f8a374-939f-11e8-9d68-cd0350b4d890.png)
> 
> **Even through my web app has this in the web.config file:**
> 
> ![image](https://user-images.githubusercontent.com/5434970/43380489-4f67e672-939f-11e8-9d0a-5f7b3d0ef8c8.png)
> 
> ![image](https://user-images.githubusercontent.com/5434970/43380498-59c79766-939f-11e8-83be-dec81094ff74.png)
> 
> Would like to enable showing Errors in Docker so I can figure out what the issue is.
> 
> Thanks,
> 
> Brian Davis

I logged in on the IIS Server inside the container, by hooking onto the IP address and its credentials. It's been a while so I'm not 100% sure on how I did it, however I wrote my thesis on the subject so I can check it later.

From there I was able to change any setting from the website running in the container. Inside IIS I had to change a few settings, so not just in the web.config, but also in IIS where you can set the error output to "Detailed" I believe. I don't know why IIS inside a container won't take the settings you give in your web.config, but that's how it is. 

So I didn't change the web.config on the host, I just had to change a few IIS settings.

**Comment by shirhatti** [comment]
@kbdavis07, @Cloudmersive Please open new issues if you continue to have problems. We do not actively monitor closed issues.
