### ISSUE TITLE
Trying to call PS1 file with the parameters from within Docker file, but no luck.

### ISSUE THREAD

**Issue by mansing2** [Microsoft/iis-docker#38]
Hi,

I have following Dockerfile where I am trying to call .PS1 file with the parameter so user can provided value against it during Docker Run command. 

```
FROM microsoft/windowsservercore
#Also used Microsoft/iis-docker
ARG AE_HOSTNAME


COPY ./resources/* C:/automic/ARA/WebUI/
CMD powershell C:\\automic\\ARA\\WebUI\\RAW.ps1 -AE_HOSTNAME $AE_HOSTNAME
```

Below is the sample Powershell
```
Param($AE_HOSTNAME)
New-Item -ItemType directory -Path C:\$AE_HOSTNAME
``` 

I am trying to run below Docker run command once the image is built. But it fails to pass the value to ps1 file

```
Docker run -it -e AE_HOSTNAME=test <imageid>
```

However when I run without parameter, powershell executes without any issue.

**Comment by mansing2** [comment]
I have used environment variable within docker file and read the value of it in Powershell. so my docker file is as per below.
```FROM microsoft/windowsservercore
ENV AE_HOSTNAME world
CMD powershell C:\\automic\\ARA\\WebUI\\RAW.ps1```

and in Powershell I have used below to read the values passed against env.
$tt = (Get-Item env:AE_HOSTNAME).value

New-Item -ItemType directory -Path C:\$tt

Any other better solution?

**Comment by shirhatti** [comment]
@mansing2 The `microsoft/iis` image on DockerHub already specifies an ENTRYPOINT. I haven't tried building an image as you described, but my naive guess is that you'll need to override the ENTRYPOINT directive and not just CMD.

**Comment by mansing2** [comment]
@shirhatti: Thank you.

I forgot to update this issue, I have defined environment variables in docker file and read their values in powershell, that solves my problem.

**Comment by vrishaligiri** [comment]
@mansing2 Can you share your code here? I'm in need of similar solution and fairly new to Docker.

**Comment by ScottEDubya** [comment]
I've been searching around for almost 2 days now trying to figure out how to get this to work, and wow, I'm grateful to have come across this thread.... 

**Dockerfile**:

```
FROM stefanscherer/node-windows:10-windowsservercore

# Install Chocolatey
RUN powershell -Command Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
RUN powershell -Command refreshenv;

RUN cinst -y 7zip

ARG VERSION
ARG NUGET_REPOSITORY
ARG NUGET_API_KEY

ENV VERSION_NUMBER=${VERSION}
ENV NUGET_REPOSITORY=${NUGET_REPOSITORY}
ENV NUGET_API_KEY=${NUGET_API_KEY}

WORKDIR /app/choco

# Note: using the ARGs as powershell arguments here doesn't work... 
# Must set them as ENV and reference the $env in the powershell script.
RUN powershell -File .\CreateChoco.ps1
```

**CreateChoco.ps1**:
```
$ErrorActionPreference = 'Stop'
$app = 'tools/project.zip'
$currentDir = $PSScriptRoot
$distDir = ($currentDir + './../dist')

Set-Location $currentDir

# update version number in nuspec file before build
(Get-Content project.nuspec) -replace '<version>__REPLACE__</version>', "<version>$($env:VERSION_NUMBER)</version>" | Set-Content project.nuspec

7z a -tzip -xr@'excludelist.txt' $app "$distDir/*"

# Do the build
choco pack
choco push "project.$env:VERSION_NUMBER.nupkg" -s $env:NUGET_REPOSITORY -k $env:NUGET_API_KEY

# reset version number
(Get-Content project.nuspec) -replace "<version>$($env:VERSION_NUMBER)</version>", '<version>__REPLACE__</version>' | Set-Content project.nuspec
```

note that inside of the powershell script, the variables can be used in two ways:
$env:VAR
or ${env:VAR}

maybe it's not too late to help your future issues! @vrishaligiri

**Comment by glenncarr** [comment]
Here's an example of how I'm passing in environment variables which are then passed in as arguments to .ps1 scripts with CMD:
```
CMD .\LoadLicense.ps1 "$env:LICENSE_ID" "$env:LICENSE_PASSWORD" ;`
    .\PrepController.ps1 `
        -DatabaseType "$env:DBTYPE" `
        -ConnectionString "$env:CONNECTION_STRING"
```
