### ISSUE TITLE
Error: hard links not supported with legacy writer

### ISSUE THREAD

**Issue by benlaan** [Microsoft/iis-docker#4]
D:\Dev\ > docker pull microsoft/aspnet
Using default tag: latest
latest: Pulling from microsoft/aspnet

9c7f9c7d9bc2: Pull complete
de5064718b3f: Extracting [==================================================>] 613.1 MB/613.1 MB
3abe74683942: Download complete
907e871a8de2: Download complete
ba066d7d1bad: Download complete
b8c8a13e99c3: Download complete
failed to register layer: re-exec error: exit status 1: output: hard links not supported with legacy writer

I am using:
- Docker version 1.13.0-dev, build 2526ae3
- Windows version Win10 (1607 - 14393.321)

Any assistance would be appreciated.

**Comment by rs38** [comment]
this disappeared when I switched to the latest 1.12.2 beta of docker. try the new OnGet deployment which ist described in the latest MSDN Container articles for Server.
[see here](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server)

**Comment by shirhatti** [comment]
@benlaan Docker 1.12.2 add support for delta images. You will need to update your docker daemon to consume the new images.
@shhsu Can we update the README to call out this Docker Daemon version requirement?

**Comment by benlaan** [comment]
I have reverted to 1.12.2 and now I'm getting an issue loading 9c7f9c7d9bc2 and de5064718b3f

They appear to be in an infinite retry loop (retrying in x seconds) however the other images have worked

Eventually it times out with the following output:

Using default tag: latest
latest: Pulling from microsoft/aspnet
9c7f9c7d9bc2: Downloading
de5064718b3f: Downloading
3abe74683942: Download complete
907e871a8de2: Download complete
ba066d7d1bad: Download complete
b8c8a13e99c3: Download complete
unknown blob

Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true

Are there any logs/diagnostics I can offer?

**Comment by shirhatti** [comment]
Ahh.

The reason the base layer shows up as an unknown blob is because you are currently trying to run this as an Linux container.

> Server:
Version: 1.12.2
API version: 1.24
Go version: go1.6.3
Git commit: bb80604
Built: Tue Oct 11 05:27:08 2016
OS/Arch: **linux/amd64**
Experimental: true

Docker for Windows allow you to switch between Windows and Linux containers. If you did install Docker for Windows you can conveniently switch between the two and you should be good.

![Switch to windows containers](https://docs.docker.com/docker-for-windows/images/config-popup-menu-win-switch-containers.png)

This is what I'm currently running
```
Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Comment by benlaan** [comment]
Great! I thought I had actually done that.. it is working now!
I'll see if I get past the original issue

Thanks

**Comment by benlaan** [comment]
Thanks.! All working now
