### ISSUE TITLE
Restarting container fails

### ISSUE THREAD

**Issue by Diego-T** [Microsoft/iis-docker#42]
The container starts without a problem but stopping and starting it again produces the following:

```
PS D:\Dev\DockerTest> docker run -d microsoft/iis
4d18[...]
PS D:\Dev\DockerTest> docker stop 4d18
4d18
PS D:\Dev\DockerTest> docker start -a 4d18
ERROR ( message:New add object missing required attributes. Cannot add duplicate collection entry of type 'add' with unique key attribute 'name' set to 'ALLUSERSPROFILE'
. )

APPCMD failed with error code 183

Failed to update IIS configuration
```
Is this scenario supported? Or should I always create a new container instead?

**Comment by jwgoedheer** [comment]
I have the same problem. 
For what I've seen the ServiceMonitor adds environment variables to the applicationhost.config. It seems like it doesn't update the dictionary correctly and that on a restart, when the keys are already added the first time,  the exception is thrown. 
For now I'm using the previous version of  ServiceMonitor.exe which doesn't update environment variables. In my setup I don't need them to be there.
Too bad there is no source or documentation of the ServiceMonitor yet.

**Comment by shirhatti** [comment]
Acknowledging this is a regression on our part. We're working to fix this.

**Comment by sebagomez** [comment]
@jwgoedheer is there a url you can share to that old ServiceMonitor?

**Comment by shirhatti** [comment]
https://github.com/Microsoft/iis-docker/raw/8ffb45926630255cff635b6c693e0efd43a96aa7/windowsservercore/ServiceMonitor.exe

**Comment by jorgecotillo** [comment]
Any hint on how I can replace the existing file in my container? I mapped my container to a host folder but once I access the folder I see no files.

**Comment by shirhatti** [comment]
> Any hint on how I can replace the existing file in my container? I mapped my container to a host folder but once I access the folder I see no files.

@jorgecotillo I'm assuming you're trying to replace `ServiceMonitor.exe`? In my opinion, the simplest way to replace it is via an [`ADD` directive](https://docs.docker.com/engine/reference/builder/#add) in your Dockerfile.

**Comment by jorgecotillo** [comment]
@shirhatti gotcha, thanks!

**Comment by shirhatti** [comment]
We have a new ServiceMonitor that should address this issue. Please feel free to give it a spin https://github.com/Microsoft/iis-docker/pull/43 and give us your feedback.

**Comment by shirhatti** [comment]
Merged in d6580f65bdf060213cd8053762591ac8b5e94746

**Comment by amitsaha** [comment]
Just wanted chime in and say that the 2.0.1.6 release still showed the behavior. I switched to the old release as per above and haven't seen the issue yet.

**Comment by liberdis** [comment]
Can confirm issue persists with 2.0.1.6 (current) ServiceMonitor.exe against microsoft/aspnet:4.7.2-windowsservercore-ltsc2016 , The July-2017 1.1.0.1 version also caused the same symptom and I have had to roll back to 1.0.0.1 as suggested at the top of this thread.

**Comment by chetanchougle** [comment]
Still no fun with microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2019 . bug exists

**Comment by chetanchougle** [comment]
@shirhatti   Even it did not work for the older ServiceMonitor . It stops the container

**Comment by wenn32** [comment]
08/2020: Issue still exists.
I had convinced business for migration to Docker.
I was working on migrating monolithic application to Azure/Container but its too unstable and unreliable.
I see lot of blockers running containers in windows.
I am going to hold off until all these basic issues are resolved.

**Comment by dbaltor** [comment]
FWIW, run into the same error with `dotnet/framework/aspnet:3.5`  image when trying to restart IIS. As already said, the workaround was to downgrade to an old ServiceMonitor version found [here](https://github.com/Microsoft/iis-docker/raw/8ffb45926630255cff635b6c693e0efd43a96aa7/windowsservercore/ServiceMonitor.exe).

**Comment by QATew** [comment]
Can anyone explain how to downgrade to an old ServiceMonitor?

**Comment by dbaltor** [comment]
You need to download the old version and include it in your container when building the image using something like
`COPY ServiceMonitor.exe /` on your Dockerfile.
