### ISSUE TITLE
Servicemonitor.exe spews a bunch of output in EntryPoint

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/iis-docker#44]
Latest version of `microsoft/iis' image produces following output to container logs. This was not the case on previous versions

```
pplied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
.
.
.
.
.
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"

```

**Comment by fkoellner** [comment]
I can confirm this. Furthermore, it causes my .Net-App to fail compilation:

>  Compilation Error
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.
Compiler Error Message: BC31007: Unable to open module file 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\test1\f3e1bcb4\e9160c86\App_global.asax.wcbcafmd.0.vb': System Error &Hc0000005& (Visual Basic internal compiler error)
Source Error: [No relevant source lines]
Source File: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\test1\f3e1bcb4\e9160c86\App_global.asax.wcbcafmd.0.vb :    Line: 0
Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1637.0

This does not occur when i use a different ENTRYPOINT in my dockerfile (which is build with FROM microsoft/iis). Currently trying to work around this issue by using SPINNER insead of servicemonitor.

**Comment by shirhatti** [comment]
@fkoellner The issue you ran into has been fixed in the July updates to the iis image.

**Comment by fkoellner** [comment]
@shirhatti Thanks for adressing this issue. But instead of using the official microsoft/iis images, i am now using my own custom made. The main reason for this decision is the lack of announcements and documentation regarding changes you guys implement. Since i´m using Docker in a productive environment, i cant afford to stumble across errors resulting from new, unannounced features.

**Comment by artisticcheese** [comment]
@fkoellner What do you use as entry point in IIS image? I agree ServiceMonitor does not produce any value apart from monitoring state of w3wp.exe. `HEALTHCHECK` already performs this roles and provided better capabilities obviously.

**Comment by fkoellner** [comment]
@artisticcheese As I said, I no longer use the official microsoft/iis-image. Instead, I build an Image FROM microsoft/windowsservercore and use powershell to install IIS and some required subfeatures. Furthermore, i ADD Spinner.exe to the Image and use this:
`SHELL ["cmd", "/S", "/C"]
	
ENTRYPOINT spinner.exe service w3svc`

**Comment by artisticcheese** [comment]
Well you still can use official IIS image and just replace ENTRYPOINT if that was the issue. What is "spinner.exe"? What does it to?

**Comment by fkoellner** [comment]
This is [Spinner](https://github.com/Ticketmaster/spinner). And yes, since my issue resolved from the ENTRYPOINT in the IIS image (which supposedly has been fixed) I could still use it - but like I said, were using Docker in Production, and unannounced, undocumented changes which cause issue are just a No Go there. Furthermore, I no longer see any gain or advantage in using the official image over an image where I´m in full control. In our case, there is no need to pass environment variables to the IIS, so I don´t have any need for the advanced ServiceMonitor.

**Comment by artisticcheese** [comment]
Wow, spinner is like `ServiceMonitor` on steroids. Have both capabilities for HTTP level monitoring as well as tail log (what I asked in other thread here for `ServiceMonitor` to accomplish.

**Comment by artisticcheese** [comment]
I just gone and ahead and did the same thing as @fkoellner. Seems that all is being done for IIS image is installing `Web-Server` and adding this useless entrypoint. 
https://artisticcheese.wordpress.com/2017/07/20/replacing-servicemonitor-exe-with-iis-error-log-events-in-windows-iis-container/

**Comment by glenncarr** [comment]
I was able to replace `ServiceMonitor.exe w3svc`, which was failing with 
```
Service 'w3svc' has been stopped

APPCMD failed with error code 13

Failed to update IIS configuration
```
with what Elton Stoneman's script:
https://blog.sixeyed.com/windows-weekly-dockerfile-13-iis-logging/

My Dockerfile now (stripped of my app-specific commands):
```# escape=`
FROM microsoft/iis:windowsservercore
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ADD . /app

WORKDIR ./app

RUN powershell -Command `
    Set-WebConfigurationProperty -p 'MACHINE/WEBROOT/APPHOST' -fi 'system.applicationHost/log' -n 'centralLogFileMode' -v 'CentralW3C'; `  
    Set-WebConfigurationProperty -p 'MACHINE/WEBROOT/APPHOST' -fi 'system.applicationHost/log/centralW3CLogFile' -n 'truncateSize' -v 4294967295; `
    Set-WebConfigurationProperty -p 'MACHINE/WEBROOT/APPHOST' -fi 'system.applicationHost/log/centralW3CLogFile' -n 'period' -v 'MaxSize'; `
    Set-WebConfigurationProperty -p 'MACHINE/WEBROOT/APPHOST' -fi 'system.applicationHost/log/centralW3CLogFile' -n 'directory' -v 'c:\iislog'; `
    Write-Host 'Done'

EXPOSE 80

ENTRYPOINT ["powershell"]
CMD Start-Service W3SVC; `  
    Invoke-WebRequest http://localhost -UseBasicParsing | Out-Null; `
    netsh http flush logbuffer | Out-Null; `
    Get-Content -path 'c:\iislog\W3SVC\u_extend1.log' -Tail 1 -Wait
```
