### ISSUE TITLE
Please redo ServiceMonitor.exe as a powershell script

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/iis-docker#45]
I think Microsoft need to allow a way for applications to send message to ServiceMonitor.exe to be output to docker (like critical events which happen on machine etc). Right now it's a black box which does not do anything except for monitoring of status of w3svc.exe. This is already can and shall be accomplished by `HEALTHCHECK` directive, ServiceMonitor becomes redundant at this point. Instead it needs to have ability to output some messages sent to it to standard output so `docker logs` can see them. Like important events generated by application.

**Comment by shirhatti** [comment]
We are definitely making amends to address the blackbox. I'm in the process on open sourcing ServiceMonitor.exe.

We, on the IIS aren't entirely convinced that moving from an exe to PowerShell script will address all your concerns. By controlling the entrypoint process, we are hoping to establish an idiomatic way of using Windows containers. We can surely consider adding features for logging. I'll leave this issue open to gather more feedback on the issue before we considering re-visiting this decision.

**Comment by shirhatti** [comment]
Closing. See https://github.com/Microsoft/IIS.ServiceMonitor/issues/1
