### ISSUE TITLE
resetting iis process stops container

### ISSUE THREAD

**Issue by evmurphy** [Microsoft/iis-docker#46]
I've manually made permissions changes to several folders on my container after it's been started with `docker-compose up`. I now want to reset the iis process to allow these changes to take effect.

## Actual Behaviour
Connecting to the container and running `iisreset /stop` produces the following error
``` 
[6f7312adf208...]: PS C:\Users\ContainerAdministrator\Documents> iisreset /stop
The background process reported an error with the following message: "The Hyper-V socket target process has ended.".
    + CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException
```
The container is then stopped and is unable to be restarted (possibly due to https://github.com/Microsoft/iis-docker/issues/42) with the following output
```
Service 'w3svc' started 
Service Change Status Notify Callback is called for service 'w3svc' with status '3'
Service 'w3svc' has been stopped 
```
## Expected Behaviour
The iis process is successfully restarted after running `iisreset /stop`, keeping the container running and updated the permission changes.

Dockerfile:
```
FROM microsoft/iis
```
docker-compose.yml
```
version: '2.1'

services:
  myservice:
    image: myimage:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
networks:
  default:
    external:
      name: nat
```
docker info:
```
PS D:\> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 69
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.92GiB
Name: xxxxxxxx
ID: 2WZX:3RRE:SJUD:SYOH:63CD:YOAA:3PWV:LX7D:SC7F:6L2I:BLBU:TVXL
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 583
 System Time: 2017-07-12T16:11:54.7832226-07:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
docker version:
```
PS D:\> docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Comment by shirhatti** [comment]
@evmurphy Is there any reason you need to make these changes after the container has already come up? We anticipated folks would bake any changes they need into their base container image and not have to manipulate IIS configuration at container run time. We consciously made the decision to have `ServiceMonitor.exe` to exit if the W3SVC is no longer running.

**Comment by arava** [comment]
I had the same issue when I had to add to convert the added folders (COnvertTo-webapplication) .net3.5.
Also have issue wrt to reisizing image size . How do we do that to accomodate application above 20GB on windows server 2016 ?

**Comment by shirhatti** [comment]
@evmurphy Closing this issue due to no reply. Feel free to re-open

**Comment by Ankit3794** [comment]
@shirhatti In some conditions we need to restart IIS without stoping the container. So, Can we achieve this with overriding any settings. I have tried to override EntryPoint but no luck.

**Comment by bariscaglar** [comment]
@Ankit3794 what do you mean by restarting IIS? You can safely recycle app pools and that won't stop the container. If you shut down the service, which iisreset will do, the service monitor will see this and exit and since by default that is the entry point program, the container will stop. You could override the EntryPoint, which I do not recommend, to something that is unrelated to IIS. Only then the container should not stop. I am not sure why that didn't work for you, but it is probably for the better.

Isn't recycling the app pool enough for your purposes?

**Comment by Ankit3794** [comment]
@bariscaglar As of now I have changed the entry point of my container to ping localhost and that does not stop container at iisreset. I will check App pool recycle will work in my case or not.

**Comment by chetanchougle** [comment]
@Ankit3794   Example  pls ?
