### ISSUE TITLE
How to install IIS OOBs in a container - Add sample dockerfiles to demonstrate how to install each OOB.

### ISSUE THREAD

**Issue by shirhatti** [microsoft/iis-docker#48]
We've seen multiple issues asking for guidance on how to install IIS OOBs like URL Rewrite and ARR in a container.
Let's try and some guidance around this.

**Comment by bariscaglar** [comment]
Agreed, the issue is now assigned to you 🥇

**Comment by tburnett80** [comment]
Been a little over a year, still nothing on this?

**Comment by bestickley** [comment]
Any updated guidance on this? I've tried using [this Dockerfile](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/windows-container-samples/iis-arr/Dockerfile) but the ExternalDiskCache module download is unavailable.

**Comment by bestickley** [comment]
I was able to solved this by installing ARR with chocolatey. See [here](https://chocolatey.org/packages/iis-arr).

**Comment by shirhatti** [comment]
> I've tried using this Dockerfile but the ExternalDiskCache module download is unavailable.

That Dockerfile references an older version of ARR that is no longer supported. The ExternalDiskCache has been made a part of the ARR installer and does not require a standalone msi

cc @john-hart
