### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by scrambledheads** [Microsoft/iis-docker#5]
I followed the instructions on this page with a File.. New Asp.Net 4.6.2 site but when I try to access the site (via the IP given using docker inspect and port 8000) I get 403 - Forbidden: Access is denied 

I'm not sure if this is a copy of https://github.com/Microsoft/Virtualization-Documentation/issues/181 

but if not to repro follow the steps as outlined in the readme.md using a default 4.6.2 file new (MVC) project from Visual Studio

**Comment by shirhatti** [comment]
Is your image on DockerHub? I can pull it down locally and have a look?
(Sorry for the late reply)

**Comment by hqer2k9** [comment]
hey there, a little bit late but maybe it helps:

you can add a local user to the admin group of the container and browse/access your iis app with it

**Comment by cozyazure** [comment]
Hey there, I am still stuck at this too. The image is `built` and `ran` properly, but whenever i visit the binded port, it always gives me `403` error. Is there anyway we can resolve this via commandline?

**Comment by hqer2k9** [comment]
issues i faced where also 403, i resolved it the following way:

1. Adding a user so i can connect trough IIS Manager:
```
RUN	NET USER testing "Password01!" /ADD
RUN	NET LOCALGROUP "Administrators" "testing" /add
```

2. Grant Permissions:
`RUN icacls "C:\IIS\*" /grant everyone:(OI)(CI)F /T`

3.  Install neccassary features
```
RUN powershell Install-WindowsFeature Web-Mgmt-Service
RUN powershell Install-WindowsFeature Web-Windows-Auth
RUN powershell Install-WindowsFeature NET-Framework-45-ASPNET
RUN powershell Install-WindowsFeature Web-Asp-Net45
RUN powershell Install-WindowsFeature NET-WCF-HTTP-Activation45
```

4.  Start Service and make it autorun
```
RUN net start wmsvc
RUN sc config WMSVC start= auto
```

```
RUN powershell -NoProfile -Command \
Set-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\WebManagement\Server -Name EnableRemoteManagement -Value 1
```

5. Expose Ports
```
EXPOSE 80
EXPOSE 8172
EXPOSE 443
```

6. Last step: 
On the IIS Server Node, go to "Feature Delegation" and give Read/Write permissions to missing stuff

never the less it strongly depends how your application work, regards autorization and so on, also i would aktivate error pages to see what kind of 403 it is, there are like 3 or 4 different kinds.

hope this helps

**Comment by kendrahavens** [comment]
I was stuck on this issue until I determined my app was not being published to an accessible folder. Note: I only ran into this problem using the windowsservercore image. My `COPY` line was incorrectly:
```Dockerfile
COPY . .
```
I changed it to the line below and it worked perfectly:
```Dockerfile
COPY . /inetpub/wwwroot
```
Hope this helps a few people running into the 403 error. Note: you still have to hit the container ip directly by running `docker ps` and copying the container hash and then running `docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" HASH` to find the container ip address.

**Comment by ravindravv** [comment]
Hi All, This is Ravi, my docker engine runnin gon windows 2016 physical machine. I pulled all images like iis, dotnet, aspnet, sql ... I successfully deployed musicstore application on the same machine. Now, I am trying to my In-house application containerization. i can able to build the image and run successfully. I am getting 403 error while the same by using container IP. Could you please help me to overcome this problem? Thanks in Advance.

**Comment by shirhatti** [comment]
It's hard to diagnose why you might be getting a 403 without more information. If you have your image pushed to DockerHub, I can pull it down and have a look?

My first guess with no additional information is that your file ACLs might prevent the AppPoolIdentity from accessing your application contents. Try ensuring the `IUSRS` group has access to the folder where your application exists.

**Comment by ravindravv** [comment]
Hi Shirhatti... Thanks for your reply.... Could you please provide your mail id to share all my work. or please send test mail to rkrk8083@gmail.com and i will reply for the same. Thanks a lot n lot. Please do the need.

**Comment by ravindravv** [comment]
Hello Sourabh, I have sent mail to you. Could you please check? Please do the need. Thanks in Advance

**Comment by ravindravv** [comment]
Hello Sourabh, Did you try at your end? Can u please do the need?

**Comment by ravindravv** [comment]
Hello All, Any inputs on my query? Please .....

**Comment by shirhatti** [comment]
@scrambledheads I'm going to close this issue since it's probably stale at this point. Feel free to open an issue if your issue persists

**Comment by barnuri** [comment]
1) Make sure that your files not ignore in .dockerignore
2) copy this Dockerfile
`
FROM microsoft/aspnet
WORKDIR /inetpub/wwwroot
COPY . /inetpub/wwwroot
# Give Full Access To Folder
RUN icacls 'c:/inetpub/wwwroot' /grant 'Everyone:(OI)(CI)F'
# Check that the files have been successfully copied
RUN dir 
`
3) docker build -t test .
4) docker run -p 8001:80 test

**Comment by barnuri** [comment]
1) Make sure that your files not ignore in .dockerignore
2) copy this Dockerfile

```
FROM microsoft/aspnet
WORKDIR /inetpub/wwwroot
COPY . /inetpub/wwwroot
# Give Full Access To Folder
RUN icacls 'c:/inetpub/wwwroot' /grant 'Everyone:(OI)(CI)F'
# Check that the files have been successfully copied
RUN dir 
```

3) docker build -t test .
4) docker run -p 8001:80 test

**Comment by saipavan9** [comment]
Anyone share the solution to this error. No Solution provided above is working

**Comment by saipavan9** [comment]
> 1. Make sure that your files not ignore in .dockerignore
> 2. copy this Dockerfile
> 
> ```
> FROM microsoft/aspnet
> WORKDIR /inetpub/wwwroot
> COPY . /inetpub/wwwroot
> # Give Full Access To Folder
> RUN icacls 'c:/inetpub/wwwroot' /grant 'Everyone:(OI)(CI)F'
> # Check that the files have been successfully copied
> RUN dir 
> ```
> 
> 1. docker build -t test .
> 2. docker run -p 8001:80 test

your solution is also not working for me. Can you please help me with this problem??

**Comment by bar-codeoasis** [comment]
i think microsoft fix there problems in diffrent docker images 
best way to check it is to use last version of visual studio 2019 and add docker support from there
its create for you dockerfile & dockerignore file

**Comment by saipavan9** [comment]
I am not able to add docker support for existing project. I can get that option for new project but I don't find that option on existing project.

**Comment by apurvakhatri** [comment]
I was using Windows 2019 with Container EC2 Instance & was facing the same issue. My project was placed in the C drive. I manually changed the permissions of the folder from read-only to full-control & it worked. Used @saipavan9 's Dockerfile.

**Comment by henrysmith** [comment]
I'm having the same issue.

I think it might be related to windows 2019.  I built it in my local on Windows 10 and it works.  However, when I try to build it in Windows Server 2019 I get the same error.

I tried changing the permissions but it didn't work 

`icacls c:\MyApps /grant Everyone:(OI)(CI)F /T`
