### ISSUE TITLE
the operation timed out... (containers on windows 10)

### ISSUE THREAD

**Issue by wxb1** [Microsoft/iis-docker#50]
I apologize I am double posting but I don't know how to reopen this issue.

I was hoping this issue was related limited resources but it is not. Any ideas you can offer would be appreciated....

https://github.com/Microsoft/iis-docker/issues/27

**Comment by bariscaglar** [comment]
Do you have other containers running into the same problem? That does sound like more of a Windows/Container layer problem rather than an IIS one. Best way to check is creating other containers, ones that don't involve IIS and seeing if they are running into the same issues or not.

**Comment by bariscaglar** [comment]
No further comments received, closing.
