### ISSUE TITLE
how to installing ASP.NET (2.0.50727) &asp.net3.5

### ISSUE THREAD

**Issue by 520luolu** [Microsoft/iis-docker#52]
how to installing ASP.NET (2.0.50727) &asp.net3.5

**Comment by bariscaglar** [comment]
The process is identical to how you'd install on non-container scenarios:

dism /online /enable-feature /all /featurename:IIS-ASPNET

(This includes 2.0 and 3.5)

**Comment by bariscaglar** [comment]
Also, if you'd like to do the same in dockerfile add:

RUN ["powershell.exe", "Enable-WindowsOptionalFeature -Online -FeatureName IIS-ASPNET"]
