### ISSUE TITLE
Possible problems with ServiceMonitor

### ISSUE THREAD

**Issue by unsafePtr** [Microsoft/iis-docker#54]
I'm using microsoft/aspnet:4.6.2 image. However question applies to all images which are using IIS.
I need to run powershell script on container startup. This one is made through specifying the ENTRYPOINT in Dockerfile:  ```ENTRYPOINT [ "powershell", "./EntryPoint.ps1"]```. At the end of ps1 file is added line to run the ServiceMonitor service: ``` C:\ServiceMonitor.exe w3svc ```. 
Does the override of entrypoint is a good idea? Can I execute script before/after starting the ServiceMonitor or there is some negative behavior?

**Comment by unsafePtr** [comment]
I've considered that probably there is no side effects. So I am closing this issue. If someone will found unexpected behavior, please, leave comment here or open a topic on stackoverflow.

**Comment by ohdihe** [comment]
Thank you for this. It work perfect for me.
