### ISSUE TITLE
cannot connect to website when using SHELL["powershell.exe"] in dockerfile

### ISSUE THREAD

**Issue by puppetSpace** [Microsoft/iis-docker#65]
I had a weird problem using the microsoft/iis image. 
I made 2 dockerfiles: 1 for hosting a website and another for hosting a REST service.
the first file contains this:
```
FROM microsoft/iis
#add asp.net feature
RUN ["powershell.exe", "Install-WindowsFeature NET-Framework-45-ASPNET"]  
RUN ["powershell.exe", "Install-WindowsFeature Web-Asp-Net45"]
#copy website to image
COPY host\\ c:\\web-app
#expose the port where the website is listening to
EXPOSE 8081
EXPOSE 60000
#add script to enable remote IIS management support
COPY \\Enable_RemoteIISManagement.ps1 c:\\Enable_RemoteIISManagement.ps1
EXPOSE 8172
#create website
RUN ["powershell.exe","New-Website -Name 'BatchmanagerWeightView' -Port 8081 -PhysicalPath 'c:\\web-app' -ApplicationPool '.NET v4.5'"]
```
when I built and ran it, I could connect to the website using the containers IP address. E.g. 172.21.156.105:8081. This was not problem.

the second file contained this:
```
FROM microsoft/iis
#add asp.net feature
SHELL ["powershell"]
RUN "Install-WindowsFeature NET-Framework-45-ASPNET" 
RUN "Install-WindowsFeature Web-Asp-Net45"
#copy website to image
COPY host\\ c:\\web-app
#add remote IIS management support
COPY \\Enable_RemoteIISManagement.ps1 c:\\Enable_RemoteIISManagement.ps1
#copy certificate
COPY dockerBatchman.pfx c:\\dockerBatchman.pfx
#import certificate pwd DockerForWindows
COPY \\Enable_Https.ps1 c:\\Enable_Https.ps1
EXPOSE 8172
#port where weight will be present
EXPOSE 60000
#expose the port where the website is listening to
EXPOSE 8081
# RUN "New-Website -Name 'RemoteWeightService' -Port 443 -PhysicalPath 'c:\\web-app' -ApplicationPool '.NET v4.5' -Ssl" 
RUN "New-Website -Name 'RemoteWeightService' -Port 8081 -PhysicalPath 'c:\\web-app' -ApplicationPool '.NET v4.5'" 
# RUN "c:\\Enable_Https.ps1 -CertificatePfxFilePath C:\\dockerBatchman.pfx -PasswordOfCert <PASSWORD>"
# CMD ["powershell.exe", "set-webBinding -Name 'RemoteWeightService' -BindingInformation '*:443:localhost'  -PropertyName 'HostHeader' -Value $env:HOSTNAME"]
```
There are some parts in comment because this web-service uses https and I wanted to exclude that this was causing the problem.
In this file I had set the shell to powershell because I had to do alot of powershell statements (which were later transferred to scripts as you can see).
When I build and ran this, It gave no issues. But when I connected to the service I got an error page stating the following:  "Server Error in '/' Application.The resource cannot be found."
I have enabled remote IIS management so check the website and everything was build correctly. I thought that maybe something was wrong with the code, so I used the website from my first dockerfile (which worked) and I still got the message. I spent a day creating builds and trying different stuff.
So I checked my first  dockerfile and saw that I didn't specify the shell there. So I removed it and changed all my RUN statements so that they used powershell:
```
FROM microsoft/iis
#add asp.net feature
RUN ["powershell.exe","Install-WindowsFeature NET-Framework-45-ASPNET"] 
RUN ["powershell.exe","Install-WindowsFeature Web-Asp-Net45"]
#copy website to image
COPY host\\ c:\\web-app
#add remote IIS management support
COPY \\Enable_RemoteIISManagement.ps1 c:\\Enable_RemoteIISManagement.ps1
#copy certificate
COPY dockerBatchman.pfx c:\\dockerBatchman.pfx
#import certificate pwd DockerForWindows
COPY \\Enable_Https.ps1 c:\\Enable_Https.ps1
EXPOSE 8172
#port where weight will be present
EXPOSE 60000
#expose the port where the website is listening to
EXPOSE 8081
# RUN "New-Website -Name 'RemoteWeightService' -Port 443 -PhysicalPath 'c:\\web-app' -ApplicationPool '.NET v4.5' -Ssl" 
RUN ["powershell.exe","New-Website -Name 'RemoteWeightService' -Port 8081 -PhysicalPath 'c:\\web-app' -ApplicationPool '.NET v4.5'"] 
# RUN "c:\\Enable_Https.ps1 -CertificatePfxFilePath C:\\dockerBatchman.pfx -PasswordOfCert <PASSWORD>"
# CMD ["powershell.exe", "set-webBinding -Name 'RemoteWeightService' -BindingInformation '*:443:localhost'  -PropertyName 'HostHeader' -Value $env:HOSTNAME"]
```
I built and ran it and now it worked. I could connect to my web-service.
So the issue I had was setting my shell, which I find weird that that is blocking something.
Is this an issue or did I make a mistake by specifying the shell?

**Comment by bariscaglar** [comment]
First impression: It looks like you would want to start with FROM microsoft/aspnet:4.7 since that's what you need. Those images will already come with ASP.NET enabled on IIS. See https://github.com/Microsoft/aspnet-docker for a list of available tags to use. There are options for 4.7.1, 4.7, 4.6.2 or even 3.5.

Second impression: Install-WindowsFeature should probably be used by /all, to enable all parent features. (If you start with asp.net image you don't need to worry about that).

I did try the SHELL directive inside the dockerfile and was able to confirm that it works. It is as such:

SHELL ["powershell"]
RUN Import-module IISAdministration; \
    New-IISSite -Name "Site" -PhysicalPath C:\site -BindingInformation "*:8000:"

See that this syntax does not have the quotation marks or the square brackets so it might be something to experiment with to find the right syntax.
