### ISSUE TITLE
Trace HTTP Errors with Failed Request Tracing

### ISSUE THREAD

**Issue by reste85** [microsoft/iis-docker#67]
How to add Tracing of failed requests? We're getting a 502.3 error when using ARR inside IIS. Do we need to add a specific module?

**Comment by shirhatti** [comment]
@reste85 No need to add a specific module, but you do need to enable the IIS tracing feature.
Additionally, I recommend creating a directory on the host that you map in to your container so that your logs persist even if the container goes away

### web.config
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
<system.webServer>
  <tracing>
    <traceFailedRequests>
      <remove path="*" />
      <add path="*">
        <traceAreas>
          <add provider="ASP" verbosity="Verbose" />
          <add provider="ASPNET" areas="Infrastructure,Module,Page,AppServices" verbosity="Verbose" />
          <add provider="ISAPI Extension" verbosity="Verbose" />
          <add provider="WWW Server" areas="Authentication,Security,Filter,StaticFile,CGI,Compression,Cache,RequestNotifications,Module" verbosity="Verbose" />
        </traceAreas>
        <failureDefinitions timeTaken="00:00:00" statusCodes="100-999" />
      </add>
    </traceFailedRequests>
  </tracing>
</system.webServer>
</configuration>
```

### Dockerfile
```Dockerfile
FROM microsoft/iis

RUN powershell -Command \
    Add-WindowsFeature Web-Http-Tracing;

WORKDIR C:\\inetpub\\wwwroot

RUN C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.applicationHost/sites "/[name='Default Web Site'].traceFailedRequestsLogging.enabled:true" /commit:apphost && \
    C:\Windows\System32\inetsrv\appcmd set config /section:sites -siteDefaults.traceFailedRequestsLogging.directory:"%SystemDrive%\inetpub\logs\FailedReqLogFiles" /commit:apphost && \
    C:\Windows\System32\inetsrv\appcmd set config /section:sites -siteDefaults.traceFailedRequestsLogging.maxLogFiles:"50" /commit:apphost

COPY web.config web.config
```

docker run -it --rm -v C:/containerlogs:C:/inetpub/logs/FailedReqLogFiles mycontainerimage

**Comment by PTC-JoshuaMatthews** [comment]
@shirhatti I get the error '&& is not a valid separator in this version of docker' when I attempt to build an image with this code. Any suggestions? If I make them 3 separate RUN statement I get an error about indexing in an array invalid position argument.

**Comment by austincrft** [comment]
I am also getting the error @PTC-JoshuaMatthews mentioned above

> ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', or '@N' where N is a numeric index into the collection. )

**Comment by bestickley** [comment]
I found [this site](https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/site/tracefailedrequestslogging#appcmdexe) helpful.
