### ISSUE TITLE
IIS PHP file 

### ISSUE THREAD

**Issue by mattcampbell15** [Microsoft/iis-docker#69]
Hey All,

the IIS image mentions it supports PHP when I copy it over doesn't seem to recognize the file at all. I was able to confirm that the copy function works properly by using a HTML file which IIS worked fine with. 

FROM microsoft/iis

RUN mkdir C:\site
COPY index.php C:\site

RUN powershell -NoProfile -Command \
    Import-module IISAdministration; \
    New-IISSite -Name "Site" -PhysicalPath C:\site -BindingInformation "*:8000:"

EXPOSE 8000

Docker image  URL : https://hub.docker.com/r/microsoft/iis/ 

Any tips to get php function to work within IIS?

Thanks.

**Comment by bariscaglar** [comment]
IIS in container does not have FastCGI enabled so it won't run php out of the box. Just like on full server, you'd need to enable that feature and install PHP before running it.

**Comment by mattcampbell15** [comment]
Ahh ok, that makes sense.   Is it possible to access the container with the IIS GUI?

**Comment by bariscaglar** [comment]
Same idea, you’d need to enable remote management feature and I’ve seen it work in practice. How much in the spirit of containers to do that is, however, I don’t know. We are planning to support manage.iis.net<http://manage.iis.net> for both management and monitoring, which will be the recommended approach going forward.

Baris.

On Jan 6, 2018, at 8:13 AM, mattcampbell15 <notifications@github.com<mailto:notifications@github.com>> wrote:


Ahh ok, that makes sense. Is it possible to access the container with the IIS GUI?

**Comment by jimmyca15** [comment]
Hey @mattcampbell15,

I wanted to give a status update on some PHP work we're doing in response to this issue. We plan to have a dockerfile with all the steps, tools, and features necessary to run PHP applications in IIS. The dockerfile in question is currently under review in pr #74 if you would like to get a head start on using it or offer any suggestions.

**Comment by jimmyca15** [comment]
A sample PHP dockerfile is now present in the samples directory. I believe this should resolve any questions of how to get PHP running in the container. If there are any further issues please let us know.

**Comment by mattcampbell15** [comment]
I'll give it a try!

**Comment by inri13666** [comment]
https://hub.docker.com/r/nanoserver/iis-php/
