### ISSUE TITLE
Dockerfile creating with CMD instead of ENTRYPOINT?

### ISSUE THREAD

**Issue by rs38** [Microsoft/iis-docker#7]
As I understood: the microsoft/iis images is build with a docker file that uses ENTRYPOINT ["C:\ServiceMonitor.exe", "w3svc"] at the end. This is not overridable with the docker run, as it would be with dockerfile created with CMD instead of ENTRYPOINT.

what is the exact purpose of choosing either way?

#https://github.com/Microsoft/Virtualization-Documentation/issues/400

**Comment by shirhatti** [comment]
Not sure I follow your question.

You can override the entrypoint at docker run time. Try this example below
```
docker run -it --entrypoint powershell microsoft/iis
```

**Comment by rs38** [comment]
you are perfectly right. Only the docs (-> see link) were incorrect.
