### ISSUE TITLE
docker pull microsoft/iis timing out

### ISSUE THREAD

**Issue by dhirastu** [Microsoft/iis-docker#70]
Get https://registry-1.docker.io/v2/microsoft/iis/manifests/sha256:5d6ad12771db3b49ca7f56c310212c200b46d2fa70ef056da0d2f4723fc3ebb2: net/http: TLS handshake timeout

Any suggestion ?

**Comment by bariscaglar** [comment]
First time takes a long time to download / extract, but mine finished right under 6 minutes. Did not see a timeout:

docker pull microsoft/iis
Using default tag: latest
latest: Pulling from microsoft/iis
5847a47b8593: Pull complete
9f887ccb8077: Pull complete
591a367f029c: Pull complete
c85ff4be242c: Pull complete
d72d8f97514e: Pull complete
914cf14bfc2d: Pull complete

Status: Downloaded newer image for microsoft/iis:latest
