### ISSUE TITLE
IIS image needs to include .NET framework optimization

### ISSUE THREAD

**Issue by artisticcheese** [microsoft/iis-docker#84]
Please see issue here (https://github.com/moby/moby/issues/33096) 
Dotnet framework have sever issue with perfomance due to issues with NGEN. Fix was distributed only to dotnet-framework image (https://github.com/dotnet/announcements/issues/33)
IIS image have to either incorporate those changes or to be built off dotnetframework.

> We are in the process of fixing Windows containers so that NGEN will work correctly. In the interim, we have updated the dotnet-framework/ images to correctly generate NGEN images. **The microsoft/windowsservercore/ images still have the performance problem that was initially reported.** We are working on updating Windows containers so that NGEN works as expected. You are recommended to use the dotnet-framework/ base image if you can, so that you can get better performance.

**Comment by bariscaglar** [comment]
@mcy94w what do you think about this? Can we start from a .NET image? What are the drawbacks of that as opposed to starting from a Windows Image, besides we would have to wait a little longer every month?

**Comment by artisticcheese** [comment]
I think much better choice will be to force dotnet framework team to distribute that fix to windowsservercore image as they planned but never did.

**Comment by bariscaglar** [comment]
> I think much better choice will be to force dotnet framework team to distribute that fix to windowsservercore image as they planned but never did.

That might be hard to do. Is there a discussion elsewhere why they reneged on that?

**Comment by artisticcheese** [comment]
Yes, it's explicitly specified that they are going to fix all windows based images here https://github.com/dotnet/announcements/issues/33

**Comment by mkvalluri** [comment]
Has this been fixed?
