### ISSUE TITLE
how to enable compression on iis 10 and changing dynamicCompressionLevel

### ISSUE THREAD

**Issue by renperez** [Microsoft/iis-docker#90]
I got the compression working but i am having a hard time changing the dynamic compression level from 0 to 4. For some reason this setting doesn't stick inside the container. This is what I have on my Dockerfile.

Add-WebConfiguration -pspath 'MACHINE/WEBROOT/APPHOST' -filter "/system.webServer/httpCompression/staticTypes" -value (@{mimeType='application/json';charset='utf-8';enabled='true'}) -Location $Site  -Force 
add-WebConfigurationProperty "/system.webServer/httpCompression/scheme[@name='gzip']" -name dynamicCompressionLevel -value 4 -Location $Site -Force

**Comment by bariscaglar** [comment]
See #73 for a good way to wait for changes to propagate. Basically, you need to wait until the changes are propagated.

**Comment by renperez** [comment]
do i insert the start-sleep in between these web-configuration changes?

**Comment by renperez** [comment]
thanks. i'll try it

**Comment by mcy94w** [comment]
Can you wrap you config command between `Begin-WebCommitDelay` and `End-WebCommitDelay`

**Comment by mcy94w** [comment]
Hi renperez:

Please reopen the issue when you still have the problem.
